### ISSUE TITLE
nxos_interfaces module in overridden state mode fails to remove configuration from target device

### ISSUE THREAD

**Issue by sswitalski18** [ansible-collections/cisco.nxos#100]
##### SUMMARY
We're attempting to use the nxos_interfaces module with Ansible 2.9.9 and a Nexus 9000v running release 9.3.(3).
When setting the nxos_interfaces module to the "overridden" state we're witnessing inconsistencies in the application of configuration.  The specific example I've been able to reproduce is trying to remove the description from an interface.

1.)  Interface is in a no shutdown mode with a description attached.
2.)  I build my Ansible Task defining the interface only to be in a no shutdown state (aka removing the description).
3.)  When the Ansible Task runs, no change is reported.  I expect the description to be removed.

I've attempted to follow [the example set forth in the documentation](https://docs.ansible.com/ansible/latest/modules/nxos_interfaces_module.html#examples) for the override state on the ansible module page to ensure that I'm using this override command correctly.  The only difference between the example given and my attempt is that eth1/1 is in a no shutdown state before running the ansible module.  The example itself (with the interface in a shutdown state) works.  But if the interface is already in a no shut (Enabled) state, the example fails to work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[nxos_interfaces](https://docs.ansible.com/ansible/latest/modules/nxos_interfaces_module.html)

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /Users/--------/Documents/GitHubProjects/---------/ansible_-----------/ansible.cfg
  configured module search path = ['/Users/--------------/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION
The Cisco Nexus 9000v is running a vanilla/base configuration.  Thus I've excluded the majority of the blank interfaces and other odds & ends from the bug report.

Running Configuration on the Nexus 9000v:
```
interface Ethernet1/1
  description Interface Ethernet1/1
  no shutdown
interface Ethernet1/2
interface Ethernet1/3
```

##### OS / ENVIRONMENT

Executed from OS X 10.14.6.  Target network device is a Nexus 9000v running on a QEMU host.  Nexus 9000v software itself is 9.3.(3).

##### STEPS TO REPRODUCE
Given the environment defined above, run the following ansible task against a Nexus 9000v chassis running 9.3.(3) software.
```
  nxos_interfaces:
    config:
      - name: Ethernet1/1
        enabled: true
      - name: Ethernet1/2
        description: 'Configured by Ansible Network'
        enabled: false
    state: overridden
  register: execution_result
```

##### EXPECTED RESULTS
Nexus 9000v Running Config after Ansible Module Execution
```
interface Ethernet1/1
  no shutdown
interface Ethernet1/2
  description Configured by Ansible Network
```

Playbook Execution and variables returned by nxos_interfaces
```
{
    "execution_result": {
        "after": [
            {
                "enabled": true,
                "name": "Ethernet1/1"
            },
            {
                "description": "Configured by Ansible Network",
                "name": "Ethernet1/2"
            }
        ],
        "before": [
            {
                "description": "Interface Ethernet1/1",
                "enabled": true,
                "name": "Ethernet1/1"
            }
        ],
        "changed": true,
        "commands": [
            "interface Ethernet1/1",
            "no description",
            "no shutdown",
            "interface Ethernet1/2",
            "description Configured by Ansible Network"
        ],
        "failed": false
    }
}
```
##### ACTUAL RESULTS
Nexus 9000v Running Config after Ansible Module Execution
```
interface Ethernet1/1
  description Interface Ethernet1/1
  no shutdown
interface Ethernet1/2
  description Configured by Ansible Network
```

Playbook Execution and variables returned by nxos_interfaces
```
{
    "execution_result": {
        "after": [
            {
                "description": "Interface Ethernet1/1",
                "enabled": true,
                "name": "Ethernet1/1"
            },
            {
                "description": "Configured by Ansible Network",
                "name": "Ethernet1/2"
            }
        ],
        "before": [
            {
                "description": "Interface Ethernet1/1",
                "enabled": true,
                "name": "Ethernet1/1"
            }
        ],
        "changed": true,
        "commands": [
            "interface Ethernet1/2",
            "description Configured by Ansible Network"
        ],
        "failed": false
    }
}
```

**Comment by NilashishC** [comment]
Hi @sswitalski18. Thank you for reporting this issue. Could you please check if the patch in https://github.com/ansible-collections/cisco.nxos/pull/102 fixes this?

**Comment by sswitalski18** [comment]
Hey @NilashishC,

Thanks so much for the quick response on this issue and the fix.  I made the modification to the file in my local environment and ran through my test procedure again.  This issue appears to have been resolved by removing the `if merged_commands:` statement.

Thank you!
