### ISSUE TITLE
RFE: Allow nxos_users to only purge local users

### ISSUE THREAD

**Issue by msilmser** [ansible-collections/cisco.nxos#107]
##### SUMMARY
Currently the nxos_user module attempts to purge all users from the device. This can sometimes cause a failure due to username length from external user accounts. Customer would like a way to enumerate only local users and then 'no' those users out.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_user.py

##### ADDITIONAL INFORMATION

```
- name: configure user - nxos
  nxos_user:
    configured_password: '{{ network_local_admin_password }}'
    name: admin
    role: '{{ network_local_admin_role }}'
    purge: yes
  when: ansible_network_os == 'nxos'


fatal: [device]: FAILED! => {"changed": false, "msg": "no username svc-ansibletest@corp.name.space\\r\\r\\n                                                           ^\\r\\n% String exceeded max length of (28) at '^' marker.\\r\\n\\rva1-wan-1(config)# "}

```

**Comment by mikewiebe** [comment]
@msilmser Are you using AAA configuration for the external accounts?  We are trying to determine the difference in how the `local` vs `external` users are configured on the device so that we can make the determination.  Thanks!

**Comment by NilashishC** [comment]
@msilmser Since we haven't received any updates from your end, we're assuming that this issue is already resolved. As such, we'll be closing this ticket. Please feel free to reopen it in case the issue still persists.
