### ISSUE TITLE
nxos_smu.py invalid character :(58) found in input when activating and committing smu

### ISSUE THREAD

**Issue by NilashishC** [ansible-collections/cisco.nxos#115]
_From @oh-c (Copied from original issue: https://github.com/ansible/ansible/issues/67570):_

##### SUMMARY
In relation to CSCvs27997 i've tried using nxos_smu.py to install, activate and commit the SMU.

Installation runs fine, but activate and commit fails but the module reports that everything is OK.

```
Hardware
  cisco Nexus7700 C7710 (10 Slot) Chassis ("Supervisor Module-3")
  System version: 8.4(1)
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_smu.py

##### ANSIBLE VERSION
```
ansible 2.9.5
```

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: true
  connection: network_cli

  tasks:

  - name: Install SMU
    nxos_smu:
      pkg: n7700-s3-dk9.8.4.1.CSCvs27997.bin
```

##### EXPECTED RESULTS
package installed, activated and committed

##### ACTUAL RESULTS

package was installed but not commited.

```
changed: [sw-01] => {
    "changed": true,
    "commands": [
        "install add bootflash:n7700-s3-dk9.8.4.1.CSCvs27997.bin",
        "install activate bootflash:n7700-s3-dk9.8.4.1.CSCvs27997.bin force",
        "install commit bootflash:n7700-s3-dk9.8.4.1.CSCvs27997.bin"
    ],
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "file_system": "bootflash:",
            "host": null,
            "password": null,
            "pkg": "n7700-s3-dk9.8.4.1.CSCvs27997.bin",
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    }
}
```

If i reproduce the commands on the switch itself i get these errors

```
sw-01# install activate bootflash:n7700-s3-dk9.8.4.1.CSCvs27997.bin force
invalid character :(58) found in input
Command contains invalid character
sw-01# install commit bootflash:n7700-s3-dk9.8.4.1.CSCvs27997.bin
invalid character :(58) found in input
```

Seems it's bothered by the bootflash path. If i remove bootflash:

```
sw-01# install activate n7700-s3-dk9.8.4.1.CSCvs27997.bin
Install operation 2 completed successfully at Wed Feb 19 12:45:25 2020
sw-01# install commit n7700-s3-dk9.8.4.1.CSCvs27997.bin
Install operation 3 completed successfully at Wed Feb 19 12:45:40 2020
```

**Comment by NilashishC** [comment]
cc @mikewiebe

**Comment by mikewiebe** [comment]
We are currently investigating this issue.  I originally suggested i (ansible/ansible#67570 ) the user try `nxos_rpm` instead of `nxos_smu`.  We should be moving away from using `nxos_smu` and instead use `nxos_rpm` for SMU's and RPMs.  I have been able to recreate the issue seen when trying to use `nxos_rpm` to apply the patch and working on a solution.
