### ISSUE TITLE
NXOS BGP Modules Don't Support Check Mode

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/cisco.nxos#119]
_From @zendritic on Jul 10, 2020 17:02_

Any plan to backport this?

Dangerous bug, should look to backporting as well.

_Originally posted by @doubleshot in https://github.com/ansible/ansible/pull/57360#issuecomment-499558582_

_Copied from original issue: ansible/ansible#70561_

**Comment by NilashishC** [comment]
@zendritic Thank you for bringing this to our notice. I have opened a backport (https://github.com/ansible/ansible/pull/70578) of the PR for Ansible 2.9 and should be available with the next 2.9 release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists or IRC channel, as appropriate:

- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
- #ansible-network on Freenode IRC

Thank you!
