### ISSUE TITLE
Adding management of Switchport mode in newer *_l2_interfaces resource module #65032

### ISSUE THREAD

**Issue by gpn005** [ansible-collections/cisco.nxos#120]
This was a bug identified and locked to collaborators with no updates. I am adding here since it does not seem to be on the list. The combined bug report is "Adding management of Switchport mode in newer *_l2_interfaces resource module #65032" which multiple people had reported previously. There is mention of something similar with IOS but this is an issue with NXOS as well (and someone mentioned Arista EOS). Unfortunately the below details on the combined bug report shows this as a "feature idea" which it is not (unless i misunderstand the classification), this is definitely a bug/missing feature compared to the module it's replacing so wanted to make sure that's clear to the Ansible team.

SUMMARY
Adding management of Switchport mode in newer *_l2_interfaces resource module, which was present in older *_l2_interface modules

ISSUE TYPE
Feature Idea

COMPONENT NAME
ios_l2_interfaces
eos_l2_interfaces
nxos_l2_interfaces

ADDITIONAL INFORMATION

This is a sample of one of the bug reports showing more details on the issue; I hit the same issue. Would appreciate an update of some kind since I see updates as of Feb/March but nothing since. The old module works without issue but is being deprecated and this is pretty core to any basic network configuration.

Sample bug report details:
Module nxos_l2_interfaces does not set switchport mode #64896:

Using module nxos_l2_interfaces does not configure switchport mode on switch interface. Only native_vlan, allowed_vlans and access vlan are pushed to the device. As a result, the configured interface remains in somewhat indeterministic state and is absolutely unsuitable for production usage.

The module also supports sending both trunk mode and access mode related commands together, which I believe should not be allowed. Sending command such as

switchport trunk native vlan 10
swtitchport access vlan 20
makes no sense and once again leads to unpredictable behavior in production.

ISSUE TYPE
Bug Report
COMPONENT NAME
nxos_l2_interfaces

ANSIBLE VERSION
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mhudec/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mhudec/.local/lib/python3.7/site-packages/ansible
  executable location = /home/mhudec/.local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]

Tested also on 2.10.0.dev0 with same results.

CONFIGURATION
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['timer', 'mail']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/mhudec/vault_password
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent

OS / ENVIRONMENT
OS: Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

LAB Devices:
Cisco Nexus9000 9000v Chassis
NXOS Version: 7.0(3)I7(4)
Image: nxos.7.0.3.I7.4.bin

ansible_connection: network_cli
ansible_network_os: nxos
Interface configuration:

LEAF-04# show running-config interface Ethernet 1/4

!Command: show running-config interface Ethernet1/4
!Time: Fri Nov 15 04:40:01 2019

version 7.0(3)I7(4)

interface Ethernet1/4

LEAF-04# show interface Ethernet 1/4
Ethernet1/4 is up
admin state is up, Dedicated Interface
  Hardware: 100/1000/10000 Ethernet, address: 5001.0004.000b (bia 5001.0004.000b
)
  MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec
  reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, medium is broadcast
  Port mode is access
  full-duplex, 1000 Mb/s
  Beacon is turned off
  Auto-Negotiation is turned on  FEC mode is Auto
  Input flow-control is off, output flow-control is off
  Auto-mdix is turned off
  Switchport monitor is off 
  EtherType is 0x8100 
  EEE (efficient-ethernet) : n/a
  Last link flapped 01:21:41
  Last clearing of "show interface" counters never
  35 interface resets
  Load-Interval #1: 30 seconds
    30 seconds input rate 0 bits/sec, 0 packets/sec
    30 seconds output rate 0 bits/sec, 0 packets/sec
    input rate 0 bps, 0 pps; output rate 0 bps, 0 pps
  Load-Interval #2: 5 minute (300 seconds)
    300 seconds input rate 0 bits/sec, 0 packets/sec
    300 seconds output rate 0 bits/sec, 0 packets/sec
    input rate 0 bps, 0 pps; output rate 0 bps, 0 pps
  RX
    0 unicast packets  0 multicast packets  0 broadcast packets
    0 input packets  0 bytes
    0 jumbo packets  0 storm suppression packets
    0 runts  0 giants  0 CRC  0 no buffer
    0 input error  0 short frame  0 overrun   0 underrun  0 ignored
    0 watchdog  0 bad etype drop  0 bad proto drop  0 if down drop
    0 input with dribble  0 input discard
    0 Rx pause
  TX
    0 unicast packets  0 multicast packets  0 broadcast packets
    0 output packets  0 bytes
    0 jumbo packets
    0 output error  0 collision  0 deferred  0 late collision
    0 lost carrier  0 no carrier  0 babble  0 output discard
    0 Tx pause
LEAF-04# show interface Ethernet 1/4 switchport 
Name: Ethernet1/4
  Switchport: Enabled
  Switchport Monitor: Not enabled 
  Switchport Isolated : Not enabled 
  Switchport Block Multicast: Not enabled 
  Switchport Block Unicast: Not enabled 
  Operational Mode: access
  Access Mode VLAN: 1 (default)
  Trunking Native Mode VLAN: 1 (default)
  Trunking VLANs Allowed: 1-4094
  Voice VLAN: none
  Extended Trust State : not trusted [COS = 0]
  Administrative private-vlan primary host-association: none
  Administrative private-vlan secondary host-association: none
  Administrative private-vlan primary mapping: none
  Administrative private-vlan secondary mapping: none
  Administrative private-vlan trunk native VLAN: none
  Administrative private-vlan trunk encapsulation: dot1q
  Administrative private-vlan trunk normal VLANs: none
  Administrative private-vlan trunk private VLANs: none
  Operational private-vlan: none
STEPS TO REPRODUCE
---
- hosts: LEAF-04
  
  tasks:
    - name: Configure Interface As L2 Interface
      nxos_interfaces:
        config:
          - name: Ethernet1/4
            enabled: True
            mode: layer2
      register: l2_output

    - name: Debug L2 Interface
      debug:
        var: l2_output.commands

    - name: Configure Interface As Trunk
      nxos_l2_interfaces:
        config:
          - name: Ethernet1/4
            trunk:
              native_vlan: 10
      register: trunk_output

    - name: Debug
      debug:
        var: trunk_output.commands
EXPECTED RESULTS
Module pushes commands ["interface Ethernet1/4", "switchport mode trunk", "switchport trunk native vlan 10"] to device.

ACTUAL RESULTS
Module pushes only commands ["interface Ethernet1/4", "switchport trunk native vlan 10"] to device.

Verbose output here

PLAY [LEAF-04] *************************************************************************************************************************************************************************************************************************

TASK [Configure Interface As L2 Interface] *********************************************************************************************************************************************************************************************
Friday 15 November 2019  14:06:05 +0100 (0:00:00.107)       0:00:00.107 ******* 
changed: [LEAF-04]

TASK [Debug L2 Interface] **************************************************************************************************************************************************************************************************************
Friday 15 November 2019  14:06:14 +0100 (0:00:09.102)       0:00:09.210 ******* 
ok: [LEAF-04] => {
    "l2_output.commands": [
        "interface Ethernet1/4", 
        "no shutdown", 
        "switchport"
    ]
}

TASK [Configure Interface As Trunk] ****************************************************************************************************************************************************************************************************
Friday 15 November 2019  14:06:14 +0100 (0:00:00.766)       0:00:09.976 ******* 
changed: [LEAF-04]

TASK [Debug] ***************************************************************************************************************************************************************************************************************************
Friday 15 November 2019  14:06:21 +0100 (0:00:06.354)       0:00:16.331 ******* 
ok: [LEAF-04] => {
    "trunk_output.commands": [
        "interface Ethernet1/4", 
        "switchport trunk native vlan 10"
    ]
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
LEAF-04                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Friday 15 November 2019  14:06:22 +0100 (0:00:00.892)       0:00:17.223 ******* 
=============================================================================== 
Configure Interface As L2 Interface --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 9.10s
Configure Interface As Trunk ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.35s
Debug --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.89s
Debug L2 Interface -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.77s
Playbook run took 0 days, 0 hours, 0 minutes, 17 seconds
From the trunk_output.command it's clear, that switchport mode is not configured. This is also confirmed by following outputs from the device:

LEAF-04# show running-config interface Ethernet 1/4

!Command: show running-config interface Ethernet1/4
!Time: Fri Nov 15 04:40:01 2019

version 7.0(3)I7(4)

interface Ethernet1/4
  switchport trunk native vlan 10
LEAF-04# show interface Ethernet 1/4
Ethernet1/4 is up
admin state is up, Dedicated Interface
  Hardware: 100/1000/10000 Ethernet, address: 5001.0004.000b (bia 5001.0004.000b
)
  MTU 1500 bytes, BW 1000000 Kbit, DLY 10 usec
  reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, medium is broadcast
  Port mode is access
  full-duplex, 1000 Mb/s
  Beacon is turned off
  Auto-Negotiation is turned on  FEC mode is Auto
  Input flow-control is off, output flow-control is off
  Auto-mdix is turned off
  Switchport monitor is off 
  EtherType is 0x8100 
  EEE (efficient-ethernet) : n/a
  Last link flapped 01:39:31
  Last clearing of "show interface" counters never
  35 interface resets
  Load-Interval #1: 30 seconds
    30 seconds input rate 0 bits/sec, 0 packets/sec
    30 seconds output rate 0 bits/sec, 0 packets/sec
    input rate 0 bps, 0 pps; output rate 0 bps, 0 pps
  Load-Interval #2: 5 minute (300 seconds)
    300 seconds input rate 0 bits/sec, 0 packets/sec
    300 seconds output rate 0 bits/sec, 0 packets/sec
    input rate 0 bps, 0 pps; output rate 0 bps, 0 pps
  RX
    0 unicast packets  0 multicast packets  0 broadcast packets
    0 input packets  0 bytes
    0 jumbo packets  0 storm suppression packets
    0 runts  0 giants  0 CRC  0 no buffer
    0 input error  0 short frame  0 overrun   0 underrun  0 ignored
    0 watchdog  0 bad etype drop  0 bad proto drop  0 if down drop
    0 input with dribble  0 input discard
    0 Rx pause
  TX
    0 unicast packets  0 multicast packets  0 broadcast packets
    0 output packets  0 bytes
    0 jumbo packets
    0 output error  0 collision  0 deferred  0 late collision
    0 lost carrier  0 no carrier  0 babble  0 output discard
    0 Tx pause
Operational Mode: access

LEAF-04# show interface Ethernet 1/4 switchport
Name: Ethernet1/4
  Switchport: Enabled
  Switchport Monitor: Not enabled 
  Switchport Isolated : Not enabled 
  Switchport Block Multicast: Not enabled 
  Switchport Block Unicast: Not enabled 
  Operational Mode: access
  Access Mode VLAN: 1 (default)
  Trunking Native Mode VLAN: 10 (VLAN0010)
  Trunking VLANs Allowed: 1-4094
  Voice VLAN: none
  Extended Trust State : not trusted [COS = 0]
  Administrative private-vlan primary host-association: none
  Administrative private-vlan secondary host-association: none
  Administrative private-vlan primary mapping: none
  Administrative private-vlan secondary mapping: none
  Administrative private-vlan trunk native VLAN: none
  Administrative private-vlan trunk encapsulation: dot1q
  Administrative private-vlan trunk normal VLANs: none
  Administrative private-vlan trunk private VLANs: none
  Operational private-vlan: none

**Comment by NilashishC** [comment]
@gpn005 The `mode` option has been already added to `nxos_l2_interfaces`. Can you please try it out and let us know?
(https://github.com/ansible-collections/cisco.nxos/blob/main/docs/cisco.nxos.nxos_l2_interfaces_module.rst#parameters)

**Comment by gpn005** [comment]
I will test and let you know. It is not in the documentation on the Ansible site. It would be helpful if the above link is noted in the modules index where I think most people look for module requirements. Thanks for sharing the link though.

Thanks,

-Geoff Novak

(610) 742-7109

Sent from my mobile

________________________________

**Comment by NilashishC** [comment]
@gpn005 This parameter has been added to the module post 2.9 release and hence, doesn't show up in the latest docs and However you can refer to https://galaxy.ansible.com/cisco/nxos which lists out all the available plugins for this collection and links to their respective docs.

**Comment by NilashishC** [comment]
@gpn005 Hello. Did you get a chance to use the updated module and check if it resolves the issue you're facing?

**Comment by NilashishC** [comment]
@gpn005 Since we haven't heard from you yet, we're assuming that the above mentioned updated module solves the issue you're facing. As such, we'll close this ticket. If you have further questions, please reopen this or reach out to us through the #ansible-network Freenode IRC channel or the [ansible-project](https://groups.google.com/forum/#!forum/ansible-project) mailing list. 

Thank you!
