### ISSUE TITLE
'nxos_command' has extra params issue

### ISSUE THREAD

**Issue by chuckjamm2001** [ansible-collections/cisco.nxos#134]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
I'm sure that I'm making a mistake but I'm unable to find a solution:
I'm attempting to run a adhoc command that will log into a nexus device and display the output of the 'show nve vni' command.  The following is one or two versions of the command that I had ran:

ansible all -i ./hosts -c network_cli -u jsmith -k -m nxos_command -a 'show nve vni' -e ansible_network_os=nxos

after entering my password, I get the following message

ERROR! this task 'nxos_command' has extra params, which is only allowed in the following modules: shell, win_shell, include_vars, add_host, raw, include_role, meta, set_facts, include, import_tasks, script, import_role, include_tasks, group_by, command, win_command

I had swapped out nxos_command with cisco.nxos.nxos_comman but got the same results
Using the raw module, got me a different results:  <host> | FAILED | rc=127 >> /bin/sh: 1: show: not found non-zero return code

Is there a more appropriate module to do the show nve vni command on a nexus device?

**Comment by NilashishC** [comment]
@chuckjamm2001 Hi! Thanks very much for your interest in Ansible. It sincerely means a lot to us.

You would need to specify the `commands` key and wrap the command in quotes for this to work:

`ansible all -i ./hosts -c network_cli -u jsmith -k -m nxos_command -a "commands='show nve vni'" -e ansible_network_os=nxos`

As such, we'll be closing this issue. If you have any further questions please feel free to stop by the following mailing list or IRC channel:

- IRC: #ansible-network on irc.freenode.net   
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks again!

**Comment by chuckjamm2001** [comment]
Thank you and bless you. I will test this out later today. I was able to
get a playbook working
