### ISSUE TITLE
ip prefix-list and route-map is missing

### ISSUE THREAD

**Issue by lkthomas** [ansible-collections/cisco.nxos#140]
I tried to search route-map and ip prefix-list setting without luck, is this a missing feature? I understand we could use cisco.nxos.nxos_command, but just want to confirm it's done on-purpose.

**Comment by NilashishC** [comment]
@lkthomas Thank you for your interest in Ansible! This seems to be a feature request for a module that deals with route-maps and ip prefix lists and we'll be tagging it at such. 

However, this module is not in our immediate roadmap and hence, it might take us some time to get to this one. Meanwhile, you can use the `nxos_config` module to configure these.

**Comment by NilashishC** [comment]
This is getting tracked in #187 and #188.

**Comment by NilashishC** [comment]
Route Maps model added in https://github.com/ansible-network/resource_module_models/pull/110

**Comment by NilashishC** [comment]
PR for route_maps: https://github.com/ansible-collections/cisco.nxos/pull/283

**Comment by NilashishC** [comment]
Fixed by https://github.com/ansible-collections/cisco.nxos/pull/283 and https://github.com/ansible-collections/cisco.nxos/pull/307.
