### ISSUE TITLE
Gather Facts issue 

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#147]
##### SUMMARY
gather facts errors

    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "members": [
                        {
                            "member": "Ethernet1/49",
                            "mode": "no"
                        },
                        {
                            "member": "Ethernet1/50",
                            "mode": "no"
                        }
                    ],
                    "name": "port-channel5"
                },
                {
                    "members": [
                        {
                            "member": "Ethernet1/53",
                            "mode": "active"
                        }
                    ],
                    "name": "port-channel100"
                },
                {
                    "members": [
                        {
                            "member": "Ethernet1/51",
                            "mode": "no"
                        }
                    ],
                    "name": "port-channel103"
                },
                {
                    "members": [
                        {
                            "member": "Ethernet1/52",
                            "mode": "no"
                        }
                    ],
                    "name": "port-channel104"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "value of mode must be one of: active, on, passive, got: no found in config -> members"
}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos gather facts
##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
linux

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by feisacrabel** [comment]
Different switch 

The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 248, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 239, in main
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py", line 125, in get_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/telemetry/telemetry.py", line 87, in populate_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 862, in __init__
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 895, in _yaml_load
AttributeError: module 'yaml' has no attribute 'FullLoader'
fatal: [ch1-spinc001]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-7582260fh0xh3f/ansible-tmp-1599771927.7670503-758232-272628040039682/AnsiballZ_nxos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 248, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 239, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 125, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/telemetry/telemetry.py\", line 87, in populate_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py\", line 862, in __init__\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_f0de8ks5/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py\", line 895, in _yaml_load\nAttributeError: module 'yaml' has no attribute 'FullLoader'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by feisacrabel** [comment]
this affects the module cisco.nxos.nxos_lag_interfaces. Bump for an update

**Comment by feisacrabel** [comment]
my suggestion is to add no to lag_interfaces.py



    argument_spec = {
        "running_config": {"type": "str"},
        "config": {
            "elements": "dict",
            "options": {
                "members": {
                    "elements": "dict",
                    "options": {
                        "member": {"type": "str"},
                        "mode": {
                            "type": "str",
                            "choices": ["no","active", "on", "passive"],
                        },
                        "force": {"type": "bool"},
                    },
                    "type": "list",
                },
                "name": {"required": True, "type": "str"},
            },

**Comment by NilashishC** [comment]
@feisacrabel Thank you for reporting this bug. This seems to be an issue with how the on-box configuration is parsed by this module. The value of `mode` should really be either of these three:
```
NXOS-9K-I5(config-if)# channel-group 100 mode ?
  active   Set channeling mode to ACTIVE
  on       Set channeling mode to ON
  passive  Set channeling mode to PASSIVE
```
Could you please share the output of `show running-config | section ^interface` from the target device so that we can debug this further?

**Comment by feisacrabel** [comment]
I think this is the relevant info you need. The nxos cli doesn't require an option to be defined

interface Ethernet1/49
  description tc1-spinc001 ethernet1/49
  switchport
  switchport mode trunk
  switchport trunk native vlan 300
  channel-group 5
  no shutdown
interface Ethernet1/50
  description tc1-spinc001 ethernet1/50
  switchport
  switchport mode trunk
  switchport trunk native vlan 300
  channel-group 5
  no shutdown
interface Ethernet1/51
  description tc1-leafc003 ethernet1/45
  switchport
  switchport mode trunk
  switchport trunk native vlan 300
  switchport trunk allowed vlan 10,17,30,66,210,250
  mtu 9216
  speed 40000
  no negotiate auto
  channel-group 103
  no shutdown
interface Ethernet1/52
  description tc1-leafc004 ethernet1/45
  switchport
  switchport mode trunk
  switchport trunk native vlan 300
  switchport trunk allowed vlan 10,17,30,66,210,250
  spanning-tree guard root
  mtu 9216
  speed 40000
  no negotiate auto
  channel-group 104
  no shutdown
interface Ethernet1/53
  switchport
  switchport mode trunk
  switchport trunk native vlan 300
  switchport trunk allowed vlan 17,25,30,250
  speed 40000
  no negotiate auto
  channel-group 100 mode active
  no shutdown

**Comment by NilashishC** [comment]
@feisacrabel Thank you for sharing the output. It was an issue in the regular expression and the "no" from the following "no shutdown" line was being picked up. The patch in #159 should fix it.
