### ISSUE TITLE
  cisco.nxos.nxos_acl_interfaces module not idempotent

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#149]
##### SUMMARY
  cisco.nxos.nxos_acl_interfaces module is not idempotent. Everyrun things return a change 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
  cisco.nxos.nxos_acl_interfaces module not idempotent

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
```yaml
---
- name: Configure Trading ACL
  include_tasks: "{{ location }}_acl.yaml"
  when: item in inventory_hostname
  with_items:
    - "{{ trading_facing_prefixes }}"
  tags:
    - nxos-acl-trading

- name: Apply Trading ACL
  cisco.nxos.nxos_acl_interfaces:
    config:
    - name: "{{ item }}"
      access_groups:
      - afi: ipv4
        acls:
        - name: "trading-{{ location }}"
          direction: in
          port: no 
  with_items:
      - "{{ external_facing_interfaces }}"
  tags:
    - nxos-acl-trading
```
Var File
---
location_number: 1
infoblox_primary: 5
infoblox_secondary: 9
infoblox_tertiary: 3
location: ch4

external_facing_interfaces:
  - "Ethernet1/8"
  - "Ethernet1/11"

##### OS / ENVIRONMENT
RHEL 

##### STEPS TO REPRODUCE
ran playbook task 

##### ACTUAL RESULTS
TASK [nxos-acl-trading : Apply Trading ACL] ************************************************************************************************************************************************
task path: /home/feisa/ansible-network/roles/nxos-acl-trading/tasks/main.yml:10
<350-spinc002> ESTABLISH LOCAL CONNECTION FOR USER: feisa
<350-spinc002> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty `"&& mkdir "` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044 `" && echo ansible-tmp-1599858242.1661716-983146-264974885648044="` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044 `" ) && sleep 0'
Using module file /home/feisa/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_acl_interfaces.py
<350-spinc002> PUT /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/tmppj2ylyub TO /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044/AnsiballZ_nxos_acl_interfaces.py
<350-spinc002> EXEC /bin/sh -c 'chmod u+x /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044/ /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044/AnsiballZ_nxos_acl_interfaces.py && sleep 0'
<350-spinc002> EXEC /bin/sh -c '/usr/libexec/platform-python /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044/AnsiballZ_nxos_acl_interfaces.py && sleep 0'
<350-spinc002> EXEC /bin/sh -c 'rm -f -r /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858242.1661716-983146-264974885648044/ > /dev/null 2>&1 && sleep 0'
changed: [350-spinc002] => (item=Ethernet1/8) => {
    "after": [
        {
            "name": "Vlan1"
        },
        {
            "name": "Vlan5"
        },
        {
            "name": "Vlan10"
        },
        {
            "name": "Vlan12"
        },
        {
            "name": "Vlan15"
        },
        {
            "name": "Vlan17"
        },
        {
            "name": "Vlan20"
        },
        {
            "name": "Vlan25"
        },
        {
            "name": "Vlan29"
        },
        {
            "name": "Vlan30"
        },
        {
            "name": "Vlan31"
        },
        {
            "name": "Vlan55"
        },
        {
            "name": "Vlan99"
        },
        {
            "name": "Vlan100"
        },
        {
            "name": "Vlan102"
        },
        {
            "name": "Vlan110"
        },
        {
            "name": "Vlan121"
        },
        {
            "name": "Vlan198"
        },
        {
            "name": "Vlan199"
        },
        {
            "name": "Vlan200"
        },
        {
            "name": "Vlan201"
        },
        {
            "name": "Vlan210"
        },
        {
            "name": "Vlan211"
        },
        {
            "name": "Vlan240"
        },
        {
            "name": "Vlan245"
        },
        {
            "name": "Vlan250"
        },
        {
            "name": "Vlan251"
        },
        {
            "name": "Vlan253"
        },
        {
            "name": "Vlan300"
        },
        {
            "name": "Vlan1000"
        },
        {
            "name": "port-channel3"
        },
        {
            "name": "port-channel5"
        },
        {
            "name": "Ethernet1/1"
        },
        {
            "name": "Ethernet1/2"
        },
        {
            "name": "Ethernet1/3"
        },
        {
            "name": "Ethernet1/4"
        },
        {
            "name": "Ethernet1/5"
        },
        {
            "name": "Ethernet1/6"
        },
        {
            "name": "Ethernet1/7"
        },
        {
            "name": "Ethernet1/8"
        },
        {
            "name": "Ethernet1/9"
        },
        {
            "name": "Ethernet1/10"
        },
        {
            "name": "Ethernet1/11"
        },
        {
            "name": "Ethernet1/12"
        },
        {
            "name": "Ethernet1/13"
        },
        {
            "name": "Ethernet1/14"
        },
        {
            "name": "Ethernet1/15"
        },
        {
            "name": "Ethernet1/16"
        },
        {
            "name": "Ethernet1/17"
        },
        {
            "name": "Ethernet1/18"
        },
        {
            "name": "Ethernet1/19"
        },
        {
            "name": "Ethernet1/20"
        },
        {
            "name": "Ethernet1/21"
        },
        {
            "name": "Ethernet1/22"
        },
        {
            "name": "Ethernet1/23"
        },
        {
            "name": "Ethernet1/24"
        },
        {
            "name": "Ethernet1/25"
        },
        {
            "name": "Ethernet1/26"
        },
        {
            "name": "Ethernet1/27"
        },
        {
            "name": "Ethernet1/28"
        },
        {
            "name": "Ethernet1/29"
        },
        {
            "name": "Ethernet1/30"
        },
        {
            "name": "Ethernet1/31"
        },
        {
            "name": "Ethernet1/32"
        },
        {
            "name": "Ethernet1/33"
        },
        {
            "name": "Ethernet1/34"
        },
        {
            "name": "Ethernet1/35"
        },
        {
            "name": "Ethernet1/36"
        },
        {
            "name": "Ethernet1/37"
        },
        {
            "name": "Ethernet1/38"
        },
        {
            "name": "Ethernet1/39"
        },
        {
            "name": "Ethernet1/40"
        },
        {
            "name": "Ethernet1/41"
        },
        {
            "name": "Ethernet1/42"
        },
        {
            "name": "Ethernet1/43"
        },
        {
            "name": "Ethernet1/44"
        },
        {
            "name": "Ethernet1/45"
        },
        {
            "name": "Ethernet1/46"
        },
        {
            "name": "Ethernet1/47"
        },
        {
            "name": "Ethernet1/48"
        },
        {
            "name": "mgmt0"
        },
        {
            "name": "loopback0"
        }
    ],
    "ansible_loop_var": "item",
    "before": [
        {
            "name": "Vlan1"
        },
        {
            "name": "Vlan5"
        },
        {
            "name": "Vlan10"
        },
        {
            "name": "Vlan12"
        },
        {
            "name": "Vlan15"
        },
        {
            "name": "Vlan17"
        },
        {
            "name": "Vlan20"
        },
        {
            "name": "Vlan25"
        },
        {
            "name": "Vlan29"
        },
        {
            "name": "Vlan30"
        },
        {
            "name": "Vlan31"
        },
        {
            "name": "Vlan55"
        },
        {
            "name": "Vlan99"
        },
        {
            "name": "Vlan100"
        },
        {
            "name": "Vlan102"
        },
        {
            "name": "Vlan110"
        },
        {
            "name": "Vlan121"
        },
        {
            "name": "Vlan198"
        },
        {
            "name": "Vlan199"
        },
        {
            "name": "Vlan200"
        },
        {
            "name": "Vlan201"
        },
        {
            "name": "Vlan210"
        },
        {
            "name": "Vlan211"
        },
        {
            "name": "Vlan240"
        },
        {
            "name": "Vlan245"
        },
        {
            "name": "Vlan250"
        },
        {
            "name": "Vlan251"
        },
        {
            "name": "Vlan253"
        },
        {
            "name": "Vlan300"
        },
        {
            "name": "Vlan1000"
        },
        {
            "name": "port-channel3"
        },
        {
            "name": "port-channel5"
        },
        {
            "name": "Ethernet1/1"
        },
        {
            "name": "Ethernet1/2"
        },
        {
            "name": "Ethernet1/3"
        },
        {
            "name": "Ethernet1/4"
        },
        {
            "name": "Ethernet1/5"
        },
        {
            "name": "Ethernet1/6"
        },
        {
            "name": "Ethernet1/7"
        },
        {
            "name": "Ethernet1/8"
        },
        {
            "name": "Ethernet1/9"
        },
        {
            "name": "Ethernet1/10"
        },
        {
            "name": "Ethernet1/11"
        },
        {
            "name": "Ethernet1/12"
        },
        {
            "name": "Ethernet1/13"
        },
        {
            "name": "Ethernet1/14"
        },
        {
            "name": "Ethernet1/15"
        },
        {
            "name": "Ethernet1/16"
        },
        {
            "name": "Ethernet1/17"
        },
        {
            "name": "Ethernet1/18"
        },
        {
            "name": "Ethernet1/19"
        },
        {
            "name": "Ethernet1/20"
        },
        {
            "name": "Ethernet1/21"
        },
        {
            "name": "Ethernet1/22"
        },
        {
            "name": "Ethernet1/23"
        },
        {
            "name": "Ethernet1/24"
        },
        {
            "name": "Ethernet1/25"
        },
        {
            "name": "Ethernet1/26"
        },
        {
            "name": "Ethernet1/27"
        },
        {
            "name": "Ethernet1/28"
        },
        {
            "name": "Ethernet1/29"
        },
        {
            "name": "Ethernet1/30"
        },
        {
            "name": "Ethernet1/31"
        },
        {
            "name": "Ethernet1/32"
        },
        {
            "name": "Ethernet1/33"
        },
        {
            "name": "Ethernet1/34"
        },
        {
            "name": "Ethernet1/35"
        },
        {
            "name": "Ethernet1/36"
        },
        {
            "name": "Ethernet1/37"
        },
        {
            "name": "Ethernet1/38"
        },
        {
            "name": "Ethernet1/39"
        },
        {
            "name": "Ethernet1/40"
        },
        {
            "name": "Ethernet1/41"
        },
        {
            "name": "Ethernet1/42"
        },
        {
            "name": "Ethernet1/43"
        },
        {
            "name": "Ethernet1/44"
        },
        {
            "name": "Ethernet1/45"
        },
        {
            "name": "Ethernet1/46"
        },
        {
            "name": "Ethernet1/47"
        },
        {
            "name": "Ethernet1/48"
        },
        {
            "name": "mgmt0"
        },
        {
            "name": "loopback0"
        }
    ],
    "changed": true,
    "commands": [
        "interface Ethernet1/8",
        "ip access-group trading-ch4 in"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access_groups": [
                        {
                            "acls": [
                                {
                                    "direction": "in",
                                    "name": "trading-ch4",
                                    "port": false
                                }
                            ],
                            "afi": "ipv4"
                        }
                    ],
                    "name": "Ethernet1/8"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "item": "Ethernet1/8"
}
<350-spinc002> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty `"&& mkdir "` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532 `" && echo ansible-tmp-1599858246.2797542-983146-40541299896532="` echo /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532 `" ) && sleep 0'
Using module file /home/feisa/ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_acl_interfaces.py
<350-spinc002> PUT /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/tmp63ysyrmn TO /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532/AnsiballZ_nxos_acl_interfaces.py
<350-spinc002> EXEC /bin/sh -c 'chmod u+x /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532/ /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532/AnsiballZ_nxos_acl_interfaces.py && sleep 0'
<350-spinc002> EXEC /bin/sh -c '/usr/libexec/platform-python /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532/AnsiballZ_nxos_acl_interfaces.py && sleep 0'
<350-spinc002> EXEC /bin/sh -c 'rm -f -r /home/feisa/.ansible/tmp/ansible-local-983104qkjstaty/ansible-tmp-1599858246.2797542-983146-40541299896532/ > /dev/null 2>&1 && sleep 0'
changed: [350-spinc002] => (item=Ethernet1/11) => {
    "after": [
        {
            "name": "Vlan1"
        },
        {
            "name": "Vlan5"
        },
        {
            "name": "Vlan10"
        },
        {
            "name": "Vlan12"
        },
        {
            "name": "Vlan15"
        },
        {
            "name": "Vlan17"
        },
        {
            "name": "Vlan20"
        },
        {
            "name": "Vlan25"
        },
        {
            "name": "Vlan29"
        },
        {
            "name": "Vlan30"
        },
        {
            "name": "Vlan31"
        },
        {
            "name": "Vlan55"
        },
        {
            "name": "Vlan99"
        },
        {
            "name": "Vlan100"
        },
        {
            "name": "Vlan102"
        },
        {
            "name": "Vlan110"
        },
        {
            "name": "Vlan121"
        },
        {
            "name": "Vlan198"
        },
        {
            "name": "Vlan199"
        },
        {
            "name": "Vlan200"
        },
        {
            "name": "Vlan201"
        },
        {
            "name": "Vlan210"
        },
        {
            "name": "Vlan211"
        },
        {
            "name": "Vlan240"
        },
        {
            "name": "Vlan245"
        },
        {
            "name": "Vlan250"
        },
        {
            "name": "Vlan251"
        },
        {
            "name": "Vlan253"
        },
        {
            "name": "Vlan300"
        },
        {
            "name": "Vlan1000"
        },
        {
            "name": "port-channel3"
        },
        {
            "name": "port-channel5"
        },
        {
            "name": "Ethernet1/1"
        },
        {
            "name": "Ethernet1/2"
        },
        {
            "name": "Ethernet1/3"
        },
        {
            "name": "Ethernet1/4"
        },
        {
            "name": "Ethernet1/5"
        },
        {
            "name": "Ethernet1/6"
        },
        {
            "name": "Ethernet1/7"
        },
        {
            "name": "Ethernet1/8"
        },
        {
            "name": "Ethernet1/9"
        },
        {
            "name": "Ethernet1/10"
        },
        {
            "name": "Ethernet1/11"
        },
        {
            "name": "Ethernet1/12"
        },
        {
            "name": "Ethernet1/13"
        },
        {
            "name": "Ethernet1/14"
        },
        {
            "name": "Ethernet1/15"
        },
        {
            "name": "Ethernet1/16"
        },
        {
            "name": "Ethernet1/17"
        },
        {
            "name": "Ethernet1/18"
        },
        {
            "name": "Ethernet1/19"
        },
        {
            "name": "Ethernet1/20"
        },
        {
            "name": "Ethernet1/21"
        },
        {
            "name": "Ethernet1/22"
        },
        {
            "name": "Ethernet1/23"
        },
        {
            "name": "Ethernet1/24"
        },
        {
            "name": "Ethernet1/25"
        },
        {
            "name": "Ethernet1/26"
        },
        {
            "name": "Ethernet1/27"
        },
        {
            "name": "Ethernet1/28"
        },
        {
            "name": "Ethernet1/29"
        },
        {
            "name": "Ethernet1/30"
        },
        {
            "name": "Ethernet1/31"
        },
        {
            "name": "Ethernet1/32"
        },
        {
            "name": "Ethernet1/33"
        },
        {
            "name": "Ethernet1/34"
        },
        {
            "name": "Ethernet1/35"
        },
        {
            "name": "Ethernet1/36"
        },
        {
            "name": "Ethernet1/37"
        },
        {
            "name": "Ethernet1/38"
        },
        {
            "name": "Ethernet1/39"
        },
        {
            "name": "Ethernet1/40"
        },
        {
            "name": "Ethernet1/41"
        },
        {
            "name": "Ethernet1/42"
        },
        {
            "name": "Ethernet1/43"
        },
        {
            "name": "Ethernet1/44"
        },
        {
            "name": "Ethernet1/45"
        },
        {
            "name": "Ethernet1/46"
        },
        {
            "name": "Ethernet1/47"
        },
        {
            "name": "Ethernet1/48"
        },
        {
            "name": "mgmt0"
        },
        {
            "name": "loopback0"
        }
    ],
    "ansible_loop_var": "item",
    "before": [
        {
            "name": "Vlan1"
        },
        {
            "name": "Vlan5"
        },
        {
            "name": "Vlan10"
        },
        {
            "name": "Vlan12"
        },
        {
            "name": "Vlan15"
        },
        {
            "name": "Vlan17"
        },
        {
            "name": "Vlan20"
        },
        {
            "name": "Vlan25"
        },
        {
            "name": "Vlan29"
        },
        {
            "name": "Vlan30"
        },
        {
            "name": "Vlan31"
        },
        {
            "name": "Vlan55"
        },
        {
            "name": "Vlan99"
        },
        {
            "name": "Vlan100"
        },
        {
            "name": "Vlan102"
        },
        {
            "name": "Vlan110"
        },
        {
            "name": "Vlan121"
        },
        {
            "name": "Vlan198"
        },
        {
            "name": "Vlan199"
        },
        {
            "name": "Vlan200"
        },
        {
            "name": "Vlan201"
        },
        {
            "name": "Vlan210"
        },
        {
            "name": "Vlan211"
        },
        {
            "name": "Vlan240"
        },
        {
            "name": "Vlan245"
        },
        {
            "name": "Vlan250"
        },
        {
            "name": "Vlan251"
        },
        {
            "name": "Vlan253"
        },
        {
            "name": "Vlan300"
        },
        {
            "name": "Vlan1000"
        },
        {
            "name": "port-channel3"
        },
        {
            "name": "port-channel5"
        },
        {
            "name": "Ethernet1/1"
        },
        {
            "name": "Ethernet1/2"
        },
        {
            "name": "Ethernet1/3"
        },
        {
            "name": "Ethernet1/4"
        },
        {
            "name": "Ethernet1/5"
        },
        {
            "name": "Ethernet1/6"
        },
        {
            "name": "Ethernet1/7"
        },
        {
            "name": "Ethernet1/8"
        },
        {
            "name": "Ethernet1/9"
        },
        {
            "name": "Ethernet1/10"
        },
        {
            "name": "Ethernet1/11"
        },
        {
            "name": "Ethernet1/12"
        },
        {
            "name": "Ethernet1/13"
        },
        {
            "name": "Ethernet1/14"
        },
        {
            "name": "Ethernet1/15"
        },
        {
            "name": "Ethernet1/16"
        },
        {
            "name": "Ethernet1/17"
        },
        {
            "name": "Ethernet1/18"
        },
        {
            "name": "Ethernet1/19"
        },
        {
            "name": "Ethernet1/20"
        },
        {
            "name": "Ethernet1/21"
        },
        {
            "name": "Ethernet1/22"
        },
        {
            "name": "Ethernet1/23"
        },
        {
            "name": "Ethernet1/24"
        },
        {
            "name": "Ethernet1/25"
        },
        {
            "name": "Ethernet1/26"
        },
        {
            "name": "Ethernet1/27"
        },
        {
            "name": "Ethernet1/28"
        },
        {
            "name": "Ethernet1/29"
        },
        {
            "name": "Ethernet1/30"
        },
        {
            "name": "Ethernet1/31"
        },
        {
            "name": "Ethernet1/32"
        },
        {
            "name": "Ethernet1/33"
        },
        {
            "name": "Ethernet1/34"
        },
        {
            "name": "Ethernet1/35"
        },
        {
            "name": "Ethernet1/36"
        },
        {
            "name": "Ethernet1/37"
        },
        {
            "name": "Ethernet1/38"
        },
        {
            "name": "Ethernet1/39"
        },
        {
            "name": "Ethernet1/40"
        },
        {
            "name": "Ethernet1/41"
        },
        {
            "name": "Ethernet1/42"
        },
        {
            "name": "Ethernet1/43"
        },
        {
            "name": "Ethernet1/44"
        },
        {
            "name": "Ethernet1/45"
        },
        {
            "name": "Ethernet1/46"
        },
        {
            "name": "Ethernet1/47"
        },
        {
            "name": "Ethernet1/48"
        },
        {
            "name": "mgmt0"
        },
        {
            "name": "loopback0"
        }
    ],
    "changed": true,
    "commands": [
        "interface Ethernet1/11",
        "ip access-group trading-ch4 in"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access_groups": [
                        {
                            "acls": [
                                {
                                    "direction": "in",
                                    "name": "trading-ch4",
                                    "port": false
                                }
                            ],
                            "afi": "ipv4"
                        }
                    ],
                    "name": "Ethernet1/11"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "item": "Ethernet1/11"
}
META: ran handlers
META: ran handlers

```

**Comment by NilashishC** [comment]
@feisacrabel Thank you for reporting this issue. I was able to reproduce it. We'll start working on a fix for this.

**Comment by NilashishC** [comment]
@feisacrabel The patch in https://github.com/ansible-collections/cisco.nxos/pull/157 along with removing `port: no` from your task (internally, the default for this key is set to "no"/"False") should fix the issue. Can you please give it a try and see if it works for you?

**Comment by feisacrabel** [comment]
Sure as soon as the PR goes through
