### ISSUE TITLE
cisco.nxos.nxos_bgp_af distance parameters returns errors 

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#154]
##### SUMMARY
Adding the distance parameters to the module invocation causes the task to crash 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_bgp_af 

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/feisa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
RHEL 8

##### STEPS TO REPRODUCE
```yaml
- name: Configure BGP Address Family Settings
  cisco.nxos.nxos_bgp_af:
    asn: "{{ item.as_number | default('15047', true) }}"
    afi: ipv4
    safi: unicast
    distance_ebgp: "20"
    distance_ibgp: "100"
    distance_local: "100"
    state: present
  tags:
    - nxos-bgp
```
##### EXPECTED RESULTS
distance 20 100 100\

##### ACTUAL RESULTS
The full traceback is:
  File "/tmp/ansible_cisco.nxos.nxos_bgp_af_payload_8qb0oivv/ansible_cisco.nxos.nxos_bgp_af_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 206, in load_config
    resp = connection.edit_config(config, replace=replace)
  File "/tmp/ansible_cisco.nxos.nxos_bgp_af_payload_8qb0oivv/ansible_cisco.nxos.nxos_bgp_af_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [tc1-spinc002]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "additional_paths_install": null,
            "additional_paths_receive": null,
            "additional_paths_selection": null,
            "additional_paths_send": null,
            "advertise_l2vpn_evpn": null,
            "afi": "ipv4",
            "asn": "15047",
            "client_to_client": null,
            "dampen_igp_metric": null,
            "dampening_half_time": null,
            "dampening_max_suppress_time": null,
            "dampening_reuse_time": null,
            "dampening_routemap": null,
            "dampening_state": null,
            "dampening_suppress_time": null,
            "default_information_originate": null,
            "default_metric": null,
            "distance_ebgp": "20",
            "distance_ibgp": "100",
            "distance_local": "100",
            "inject_map": null,
            "maximum_paths": null,
            "maximum_paths_ibgp": null,
            "networks": null,
            "next_hop_route_map": null,
            "provider": null,
            "redistribute": null,
            "retain_route_target": null,
            "safi": "unicast",
            "state": "present",
            "suppress_inactive": null,
            "table_map": null,
            "table_map_filter": null,
            "vrf": "default"
        }
    },
    "msg": "distance None 100 100\r\r\n                                         ^\r\n% Invalid number at '^' marker.\r\n\rtc1-spinc002(config-router-af)# "
}

**Comment by NilashishC** [comment]
@feisacrabel I was not able to reproduce this issue and it worked as expected for me. Is there any existing BGP config on the device that you're running this against? If so, do you mind sharing that so I can check if this issue is reproducible using that as a base config?

**Comment by feisa** [comment]
no bgp config, same issue "distance None 100 100\r\r\n

**Comment by NilashishC** [comment]
@feisa Can you please share the NX-OS version you are running this against? I'll try to check if it is reproducible with that particular appliance if I'm able to get hold of one.

**Comment by feisa** [comment]
Software
  BIOS: version 07.66
 NXOS: version 9.3(3)

**Comment by praveenramoorthy** [comment]
@feisa I tried to repro this issue with same software(NXOS/Python/Ansible) versions and playbook as yours and it worked as expected.

Software
  BIOS: version 07.67
  NXOS: version 9.3(3)

ansible-playbook 2.9.13
  config file = /Users/prramoor/Ansible/ansible-check/ansible.cfg
  configured module search path = ['/Users/prramoor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/prramoor/Ansible/ansible-check/ansible/lib/ansible
  executable location = /Users/prramoor/Ansible/ansible-check/ansible/bin/ansible-playbook
  python version = 3.6.8 (default, Dec 22 2020, 20:13:57) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]

Is there any specific commands/sequence I need to follow before executing this playbook?

**Comment by NilashishC** [comment]
@feisa Since we haven't heard from you yet, we are assuming that the issue is resolved. Also, please note that the `nxos_bgp_af` module has been deprecated and replaced by `nxos_bgp_neighbor_address_family` resource module. As such, we'll be closing this ticket. If you wish to discuss this further, please feel free to reach out to us either through the ansible-network Freenode IRC channel or through the ansible-project mailing list. Thank you for your interest in Ansible!
