### ISSUE TITLE
BGP Module supports aggregate addresses

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#156]
##### SUMMARY
Request the BGP process modules support aggregate addresses in order to summarize subnets to peers, similar to ospf summery and range prefixes 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.nxos.nxos_bgp_af

##### ADDITIONAL INFORMATION
router bgp 65200
  router-id 1.1.1.1
  log-neighbor-changes
  address-family ipv4 unicast
    network 10.0.1.0/28
    aggregate-address 10.0.1.0/4/27

**Comment by NilashishC** [comment]
This has been addressed in the upcoming nxos_bgp_address_family module which will deprecate the nxos_bgp_af module.
https://github.com/ansible-collections/cisco.nxos/pull/245
