### ISSUE TITLE
cisco.nxos.nxos_user support for json native

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#163]
##### SUMMARY
looks to change the following collections/ansible_collections/cisco/nxos/plugins/modules/nxos_user.py

```
def map_config_to_obj(module):
    out = run_commands(module, ["show user-account | json "])
    data = out[0]

    objects = list()

to 

def map_config_to_obj(module):
    out = run_commands(module, ["show user-account | json native"])
    data = out[0]
```
This will allow support for all nxos platform devices 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_user 

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### OS / ENVIRONMENT
mds/9ks

##### STEPS TO REPRODUCE
```
---
- name: Change Local Admin Password
  cisco.nxos.nxos_user:    
    name: "{{ localusername }}"
    role: network-admin
    configured_password: "{{ localpassword }}"
  tags:
    - nxos-users
```

##### EXPECTED RESULTS
```
The full traceback is:
  File "/tmp/ansible_cisco.nxos.nxos_user_payload_r7iwelug/ansible_cisco.nxos.nxos_user_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 177, in run_commands
    out = connection.run_commands(commands, check_rc)
  File "/tmp/ansible_cisco.nxos.nxos_user_payload_r7iwelug/ansible_cisco.nxos.nxos_user_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[WARNING]: Module did not set no_log for update_password
fatal: [la3-sanmc002]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "configured_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name": "admin",
            "provider": null,
            "purge": false,
            "role": "network-admin",
            "roles": [
                "network-admin"
            ],
            "sshkey": null,
            "state": "present",
            "update_password": "always"
        }
    },
    "msg": "show user-account | json\r\r\n                                      ^\r\n% Incomplete command at '^' marker.\r\n\rla3-sanmc002# "
```

**Comment by mikewiebe** [comment]
@feisa What platform are you testing?  We need to make sure that adding the cli option `native` on the end will work for the entire list of platforms we support.

**Comment by feisa** [comment]
Software
  BIOS:      version 2.1.17
  loader:    version N/A
  kickstart: version 8.4(1)
  system:    version 8.4(1)
  BIOS compile time:       01/08/14
  kickstart image file is: bootflash:///m9100-s5ek9-kickstart-mz.8.4.1.bin
  kickstart compile time:  6/30/2019 23:00:00 [06/15/2019 04:15:24]
  system image file is:    bootflash:///m9100-s5ek9-mz.8.4.1.bin
  system compile time:     6/30/2019 23:00:00 [06/15/2019 05:44:25]

**Comment by mikewiebe** [comment]
@feisa Thanks!  Let me follow up with a few teams internally to make sure this change will work ok across multiple platforms.
