### ISSUE TITLE
ansible.netcommon.restconf_get doesn't work with nxos

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/cisco.nxos#172]
```    
    if output == "xml":
        accept = "application/yang-data+xml"
    if output == "json":
        accept = "application/yang.data+json"
```
may be an issue in netcommon/module_utils/network/restconf/restconf.py because no `accept` is set.

putting this here to talk more about it

**Comment by Qalthos** [comment]
This definitely belongs in netcommon instead of nxos.

What is `output` if not one of those two?

**Comment by NilashishC** [comment]
Even with output set to json, this doesn't work. The data returned by send_request() is empty. Closing this in favour of https://github.com/ansible-collections/ansible.netcommon/issues/306 since the fix will go in netcommon.
