### ISSUE TITLE
aggregate for nxos_vlans, nxos_interfaces, nxos_l2_interfaces, nxos_l3_interfaces

### ISSUE THREAD

**Issue by roundtripdelay** [ansible-collections/cisco.nxos#196]
##### SUMMARY
The deprecated modules cisco.nxos.nxos_vlan, cisco.nxos.interface, cisco.nxos.nxos_l2_interface and cisco.nxos.nxos_l3_interfaces all support the aggregate parameter. The modules that replace these don't support aggregate -- cisco.nxos.nxos_vlans, cisco.nxos.interface, cisco.nxos.nxos_l2_interfaces and cisco.nxos.nxos_l3_interfaces. 

Are there plans to add the aggregate parameter to the new modules?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
There might be more modules lacking aggregate, but these specifically:

cisco.nxos.nxos_vlans
cisco.nxos.nxos.interfaces
cisco.nxos.nxos_l2_interfaces
cisco.nxos.nxos_l3_interfaces

##### ADDITIONAL INFORMATION

Aggregate has a lot of benefits as already documented at https://www.ansible.com/blog/accelerate-ansible-networking-aggregate-resources.

**Comment by NilashishC** [comment]
@roundtripdelay Thanks very much for your interest in Ansible. It sincerely means a lot to us.

The `config` key for all the resource modules you mentioned are list of dictionaries, which means that you can "aggregate" all the vlan configs in a task and have it execute only once (similar to what the `aggregate` key did for the older modules). Please refer to the examples given in the documentation of these Resource Modules and try them out to see it works.

As such, we'll be closing this ticket. If you'd like to discuss this further please feel free to connect with us either through the following mailing list or the IRC channel.

IRC: #ansible-network on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
