### ISSUE TITLE
Doc changes to reflect MDS

### ISSUE THREAD

**Issue by srbharadwaj** [ansible-collections/cisco.nxos#211]
1) add MDS details here (https://docs.ansible.com/ansible/latest/network/user_guide/platform_nxos.html)

2) In this doc (https://docs.ansible.com/ansible/latest/collections/cisco/nxos/) it says “Configuration of vsan” for vsan module, can we change it to “Configuration of vsan for Cisco NXOS  MDS Switches” ..same way for other MDS modules nxos_devicealias and nxos_zone_zoneset.

**Comment by NilashishC** [comment]
The module short descriptions are updated in this PR: https://github.com/ansible-collections/cisco.nxos/pull/232.
