### ISSUE TITLE
Bugfix show module nxos cli

### ISSUE THREAD

**Issue by gerardocastaldo** [ansible-collections/cisco.nxos#219]
##### SUMMARY
In order to resolve parsing problem in parse_module function with old nexus releases i would suggest you this implementation. I know that new releases this problem isn't exist because it use api requests or json formatted output for cli requests, but in many case i need to work with old nexus releases.

Sorry me for the request but i haven't skills to produce new package and submit it.

```
    def parse_module(self, data):
        objects = list()
        for line in data.splitlines():
            if line == "":
                break
            if line[0].isdigit():
                obj = {}
                match = re.search(r"^(?P<Mod>\d{1,3})\s+(?P<Ports>\d{1,5})\s+(?P<Module_Type>.{1,34})\s+(?P<Model>.{1,23})\s+(?P<Status>.{1,13})$", line, re.M)
                if match:
                    obj["ports"] = match.group('Ports')
                    obj["type"] = re.sub("\s+$", "", match.group('Module_Type'))
                    obj["model"] = re.sub("\s+$", "", match.group('Model') )
                    obj["status"] = re.sub("\s+$", "", match.group('Status') )
                objects.append(obj)
        return objects

```
    
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

collections/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by NilashishC** [comment]
@gerardocastaldo Could you please share which version of NX-OS you are running the playbook against?

**Comment by gerardocastaldo** [comment]
Hi, follow the show version.

Nx5548U-SSC# sh version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2017, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Software
  BIOS:      version 3.6.0
  loader:    version N/A
  kickstart: version 5.2(1)N1(9b)
  system:    version 5.2(1)N1(9b)
  power-seq: Module 1: version v3.0
             Module 2: version v1.0
             Module 3: version v5.0
  uC:        version v1.2.0.1
  SFP uC:    Module 1: v1.1.0.0
  BIOS compile time:       05/09/2012
  kickstart image file is: bootflash:///n5000-uk9-kickstart.5.2.1.N1.9b.bin
  kickstart compile time:  1/31/2017 0:00:00 [01/31/2017 13:17:34]
  system image file is:    bootflash:///n5000-uk9.5.2.1.N1.9b.bin
  system compile time:     1/31/2017 0:00:00 [01/31/2017 14:06:58]


Hardware
  cisco Nexus5548 Chassis ("O2 32X10GE/Modular Universal Platform Supervisor")
  Intel(R) Xeon(R) CPU         with 8263840 kB of memory.
  Processor Board ID FOC18413S1L

  Device name: Nx5548U-SSC
  bootflash:    2007040 kB

Kernel uptime is 991 day(s), 21 hour(s), 46 minute(s), 17 second(s)

Last reset
  Reason: Unknown
  System version: 5.2(1)N1(9b)
  Service:

plugin
  Core Plugin, Ethernet Plugin, Fc Plugin, Virtualization Plugin

**Comment by NilashishC** [comment]
@gerardocastaldo Thank you for sharing the required information. It appears that the target device is running a NX-OS that falls outside the [Cisco Nexus platform support matrix](https://docs.ansible.com/ansible/latest/network/user_guide/platform_nxos.html#id2) we have documented in the platform guide. Also, the minimum recommended NX-OS version for Nexus 5500 platform is 7.3(8)N1(1), as specified in this Cisco documentation: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus5500/sw/release/recommended_releases/n5500_recommended_nx-os_releases.html

As such, we will go ahead and close this ticket. If you have further queries please feel free to reach out to us through the ansible-project mailing list or the #ansible-network Freenode IRC channel.

Thank you for your interest in Ansible!
