### ISSUE TITLE
Issue gathering facts. 

### ISSUE THREAD

**Issue by acarte26** [ansible-collections/cisco.nxos#223]
##### SUMMARY
Hello, 

I am somewhat new to ansible especially as it relates the nxos modules. I'm trying to write a very basic program to pull the CPU info on nexus switches. I'm getting an error when i try to register than into a variable and show it as output. Any assistance with this would be GREATLY appreciated. Below is my playbook and the error:
```
---
 - hosts: nxosswitches
   gather_facts: true
   vars_files:
    - "nxos.yml"

   tasks:
     - name: Gather hardware facts
       nxos_command:
        commands:
          - show processes cpu history
        register: cpu

     - debug: msg = "{{ cpu }}"
```
OUTPUT/Error:
TASK [Gather hardware facts] *****************************************************************************************************
fatal: [a000nsw4]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (nxos_command) module: register Supported parameters include: auth_pass, authorize, commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, transport, use_ssl, username, validate_certs, wait_for"}

Now I obviously understand(i think) what the bug is saying so i moved register back a few spaces so its not a part of that code block. However when I do that nothing gets registered into a variable. 

Can someone give some guidance on this? Thanks 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by allenrobel** [comment]
Hi,

Below is an example where register is used in a few tasks to save the output from an NXOS device as both text and json to files.

Regards,

Allen

"Ridding the world of uncalculated packets, one engineer at a time."

https://www.packetcalc.com


   name: nxos_command task
   tasks:
   -   cisco.nxos.nxos_command:
           commands:
           - show clock
           interval: 1
           match: all
           retries: 10
       name: 'nxos_command: show clock'
       register: output
   -   local_action: copy content="{{ output.stdout[0] }}" dest="/tmp/show_clock.txt"
       name: RegisterSave
       register: null
       vars:
           ansible_connection: local
   -   cisco.nxos.nxos_command:
           commands:
           - show ip bgp summary
           interval: 1
           match: all
           retries: 10
       name: 'nxos_command: show ip bgp summary'
       register: output
   -   local_action: copy content="{{ output.stdout[0] }}" dest="/tmp/show_ip_bgp_summary.txt"
       name: RegisterSave
       register: null
       vars:
           ansible_connection: local
   -   cisco.nxos.nxos_command:
           commands:
           -   command: show bgp process
               output: json
           interval: 1
           match: all
           retries: 10
       name: 'nxos_command: output json, show bgp process'
       register: output
   -   local_action: copy content="{{ output.stdout[0] }}" dest="/tmp/show_bgp_process.json"
       name: RegisterSave
       register: null
       vars:
           ansible_connection: local

**Comment by NilashishC** [comment]
@acarte26 The `register` keyword in the playbook you shared is at the wrong indent level. The following should resolve this issue.

```yaml
---
 - hosts: nxosswitches
   gather_facts: true
   vars_files:
    - "nxos.yml"

   tasks:
     - name: Gather hardware facts
       nxos_command:
        commands:
          - show processes cpu history
       register: cpu

     - debug: msg = "{{ cpu }}"
```
As such, we'll be closing this ticket. If you have further questions, please feel free to reach out to us through the #ansible-network IRC channel or the ansible-project mailing list.

Thank you for you interest in Ansible!
