### ISSUE TITLE
nxos_pim_interface: hello_interval inappropriately multiplied by 1000 on N9K

### ISSUE THREAD

**Issue by allenrobel** [ansible-collections/cisco.nxos#226]
##### SUMMARY
On N9K, the pim hello-interval unit is milliseconds in a range of 1-18724286.

The nxos_pim_interface module multiplies user input by 1000.  There are two ramifications of this:

1. Users cannot enter values below 1 second (1ms is converted to 1000ms == 1 second).
2.  The maximum allowed value (18724286) results in an error since it is converted to 18724286000 and results in NXOS rejecting it with "CLI execution error: % Invalid number"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_pim_interface

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /Users/arobel/.ansible.cfg
  configured module search path = ['/Users/arobel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arobel/ansible-latest/lib/python3.9/site-packages/ansible
  executable location = /Users/arobel/ansible-latest/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### CONFIGURATION

```
CACHE_PLUGIN_TIMEOUT(/Users/arobel/.ansible.cfg) = 86400
DEFAULT_LOG_PATH(/Users/arobel/.ansible.cfg) = /tmp/ansible.log
HOST_KEY_CHECKING(/Users/arobel/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
NXOS: version 9.3(6)
N9K-C93180YC-FX

##### STEPS TO REPRODUCE
Run Task_1 to reproduce issue where user cannot enter values less than 1 second.
Run Task_2 to reproduce issue where user cannot enter maximum allowable value of 18724286 milliseconds.

Task_1

```yaml
    tasks:
    -   cisco.nxos.nxos_pim_interface:
            hello_interval: '1'
            interface: Ethernet1/49
            state: present
```

Task_2

```yaml
    tasks:
    -   cisco.nxos.nxos_pim_interface:
            hello_interval: '18724286'
            interface: Ethernet1/49
            state: present
```

##### EXPECTED RESULTS

The value the user enters for hello_interval should not be multiplied by 1000.

##### ACTUAL RESULTS

The value the user enters for hello_interval is multiplied by 1000.

1. NX-OS ip pim hello-interval CLI options.

```
switch(config-if)# ip pim hello-interval ?
  <1-18724286>  Interval in milliseconds
                *Default value is 30000
```

2. nxapi-server log when hello_interval is set to 1 millisecond by the user:

```
2021 January 17 02:27:46.760 pterm_write_to_vsh:527 pid:15577 In vsh [16] Writing cmd "ip pim hello-interval 1000"
2021 January 17 02:27:46.788 pterm_write_to_vsh:603 pid:15577 Cmd 'ip pim hello-interval 1000' returned with '0'
```

2. nxapi-server log when hello_interval is set to 18724286 milliseconds by the user:

```
2021 January 17 02:26:02.581 pterm_write_to_vsh:527 pid:15481 In vsh [16] Writing cmd "ip pim hello-interval 18724286000"
2021 January 17 02:26:02.586 pterm_write_to_vsh:603 pid:15481 Cmd 'ip pim hello-interval 18724286000' returned with '16'
2021 January 17 02:26:02.586 pterm_write_to_vsh:606 pid:15481 Cmd 'ip pim hello-interval 18724286000' had failure '16'
2021 January 17 02:26:02.586 _ins_api_cli_cmd_conf:621 pid:15481 Failed for cmd: ip pim hello-interval 18724286000 code 16
```

**Comment by NilashishC** [comment]
@allenrobel Thank you for reporting this issue. Since updating the current behaviour would be a breaking change, a new option `hello_interval_ms` was added in #255, which when set to True, prevents the `hello_interval` from being converted into milliseconds. When set to False on kept unset, the module behaves as before.

**Comment by allenrobel** [comment]
Thanks much @NilashishC for the followup.  This solution looks good.
