### ISSUE TITLE
nxos_bgp_global does not support bfd while nxos_bgp_neighbor is going to be deprecated

### ISSUE THREAD

**Issue by KennyVdN** [ansible-collections/cisco.nxos#241]
##### SUMMARY

enable bfd on bgp neighbor
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_bgp_global
##### ADDITIONAL INFORMATION

enabling bfd on a bgp neighbor configuration

```yaml

```

**Comment by NilashishC** [comment]
@KennyVdN the patch in #242 should fix this. Thanks for reporting this to us.
