### ISSUE TITLE
Private module attribute moved in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/cisco.nxos#267]
##### SUMMARY

Argument spec validation has changed in Ansible Core 2.11. The following private attribute call should be changed to use the public variable:

```
cisco.nxos/plugins/modules/nxos_user.py
336:        type_checker = module._CHECK_ARGUMENT_TYPES_DISPATCHER[value_type]  # --> ansible.module_utils.common.parameters.DEFAULT_TYPE_VALIDATORS
```

The private attribute is available for backwards compatibility only.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`nxos_user.py`

##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by Qalthos** [comment]
We can't move to the new location while we support versions < 2.11, and the private attribute will persist for the foreseeable future.

I'm keeping the original issue at https://github.com/ansible-collections/ansible.netcommon/issues/186 open for now to coordinate efforts around replacing it if and when that becomes feasible
