### ISSUE TITLE
mds interface FC

### ISSUE THREAD

**Issue by Aglidic** [ansible-collections/cisco.nxos#279]
hello
i have try to use the module interfaces to bring up my fc interfaces on mds switches but it doesn't work.

I have try to use the commands module. If i set the interface name directly in the code it works. But if i try to use a variable for the interface name command failed because of some \r\r\n added to the command line.

regards

**Comment by Aglidic** [comment]
Example:
this works:
- name: Set port to no shut
  cisco.nxos.nxos_command:
    commands:
      - configure terminal
      - command: 'interface fc1/34; no shut ;'

this doesn't work:
- name: Set port to no shut
  cisco.nxos.nxos_command:
    commands:
      - configure terminal
      - command: 'interface "{{ interface_number }}" ; no shut ;'

**Comment by Aglidic** [comment]
Here is output with interface harcoded 

{
    "changed": false,
    "stdout": [
        "Enter configuration commands, one per line.  End with CNTL/Z.",
        ""
    ],
    "stdout_lines": [
        [
            "Enter configuration commands, one per line.  End with CNTL/Z."
        ],
        [
            ""
        ]
    ],
    "invocation": {
        "module_args": {
            "commands": [
                "configure terminal",
                {
                    "command": "interface fc1/3 ; no shut ",
                    "output": "text",
                    "prompt": null,
                    "answer": null,
                    "newline": true,
                    "sendonly": false,
                    "check_all": false
                }
            ],
            "match": "all",
            "retries": 10,
            "interval": 1,
            "wait_for": null,
            "provider": null
        }
    },
    "_ansible_no_log": false
}

**Comment by Aglidic** [comment]
Here is the result with variable:

1) my extra vars: machine_port: fc1/3

2) error message:
{
    "msg": "interface \"fc1/3\" ; no shut \r\r\n                          ^\r\nInvalid interface format at '^' marker.\r\n\rsfc00p(config)# ",
    "invocation": {
        "module_args": {
            "commands": [
                "configure terminal",
                {
                    "command": "interface \"fc1/3\" ; no shut ",
                    "output": "text",
                    "prompt": null,
                    "answer": null,
                    "newline": true,
                    "sendonly": false,
                    "check_all": false
                }
            ],
            "match": "all",
            "retries": 10,
            "interval": 1,
            "wait_for": null,
            "provider": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

**Comment by NilashishC** [comment]
cc @srbharadwaj

**Comment by Aglidic** [comment]
Hello,

I finally found a workaround to make it work

Envoyé depuis mon téléphone Huawei


-------- Message original --------
De : Suhas Bharadwaj ***@***.***>
Date : mar. 11 mai 2021 à 08:48
À : "ansible-collections/cisco.nxos" ***@***.***>
Cc : Anthony Glidic ***@***.***>, Mention ***@***.***>
Objet : Re: [ansible-collections/cisco.nxos] mds interface FC (#279)

@Aglidic<https://github.com/Aglidic> can you try

  *   command: 'interface {{ interface_number }} ; no shut ;'
There should not be any quotes.. the reason you are seeing the error is that there are quotes around the interface name
