### ISSUE TITLE
File copy doesn't support ansible_ssh_common_args

### ISSUE THREAD

**Issue by tgupta3** [ansible-collections/cisco.nxos#284]
https://github.com/ansible-collections/cisco.nxos/blob/0c6ec645db52382db84a71dfe7fc4ba26ab7f4ae/plugins/action/nxos_file_copy.py#L414

ansible_ssh_common_args is ignored because of the ssh command being hardcoded.  This was difficult to troubleshoot as well the error message didn't indicate where the session was stuck. Suggest adding outcome['error_data'] to the message.

**Comment by NilashishC** [comment]
Hi @tgupta3. Thank you for reporting this. We have started working on getting this fixed. Apologies for the delay.

**Comment by NilashishC** [comment]
The patch in #421 should fix this. However, we need https://github.com/ansible-collections/ansible.netcommon/issues/296 to be resolved in order for network_cli to pick up ssh_common_args correctly. I have shared a workaround in the thread.
