### ISSUE TITLE
unable to set terminal parameters - network_cli connecting to Nexus

### ISSUE THREAD

**Issue by ramanga84** [ansible-collections/cisco.nxos#289]
##### SUMMARY

Unable to execute playbook successfully, as the module fails with unexpected error. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_command
##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.9 (Maipo)

Network device 
Nexus7700
Software
  BIOS:      version 3.1.0
  kickstart: version 6.2(22)
  system:    version 6.2(22)

##### STEPS TO REPRODUCE

Just define the vars in inventory as below and run the playbook against a nexus device. 
[capcs:vars]
ansible_connection=network_cli
ansible_network_os=nxos
ansible_password='password'
ansible_user=admin
ansible_become_password='becomepassword'

```yaml
[root@sb-hostname ansible-projects]# cat nxos.yml |grep -v '#'
---
- name: Check nxos
  hosts: all
  connection: network_cli
  gather_facts: false
  tasks:
    - name: run command on nexus
      nxos_command:
        commands:
             - show version
             - show license
      register: result

    - debug:
        var: result
```

##### EXPECTED RESULTS

Provide the output for show license, show version commands in nexus

##### ACTUAL RESULTS

```paste below
[root@sb-hostname ansible-projects]# ansible-playbook nxos.yml -i nexus-inventory -vvv
ansible-playbook 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/ansible_dev/ansible-projects/nexus-inventory as it did not pass its verify_file() method
script declined parsing /home/ansible_dev/ansible-projects/nexus-inventory as it did not pass its verify_file() method
auto declined parsing /home/ansible_dev/ansible-projects/nexus-inventory as it did not pass its verify_file() method
Parsed /home/ansible_dev/ansible-projects/nexus-inventory inventory source with ini plugin

PLAYBOOK: nxos.yml *************************************************************************************************************************************************
1 plays in nxos.yml

PLAY [Check nxos] **************************************************************************************************************************************************
META: ran handlers

TASK [run command on nexus] ****************************************************************************************************************************************
task path: /home/ansible_dev/ansible-projects/nxos.yml:7
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/nxos.py", line 136, in run
    out = conn.get_prompt()
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ConnectionError: unable to set terminal parameters

fatal: [TP-CS04]: FAILED! => {}

MSG:

Unexpected failure during module execution.


PLAY RECAP *********************************************************************************************************************************************************
TP-CS04-L2                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[root@sb-hostname ansible-projects]#
```

**Comment by NilashishC** [comment]
@ramanga84 This generally happens when the `ansible_user` is unable to execute the following commands `terminal length 0` and `terminal width 511` on the device. Could you please confirm if you are able to do this directly on the target device CLI? If yes, please share the persistent logs from the playbook run. Steps to enable it are mentioned here - https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#enabling-networking-device-interaction-logging.

**Comment by ramanga84** [comment]
We are trying to execute this as a readonly user. AFAIK, the terminal length can be set only by a privileged user. So is it not possible to connect as a readonly user to nexus at all ?

**Comment by NilashishC** [comment]
@ramanga84 We require the terminal length and width to be appropriately set before any other command is executed to ensure that the underlying connection (network_cli) gets the entire data (along with the prompt) instead of having to deal with pagination issues which would inadvertently result in a command timeout.

However, you can switch to `ansible_connection: httpapi` which leverage the platform's NX-API. With this connection type, Ansible doesn't attempt to configure the terminal commands.

As such, I'll be closing this issue. If you wish to discuss this further, please feel free to reach out to us through the #ansible-network IRC channel or the ansible-project mailing list.

Thank you!
