### ISSUE TITLE
nxos_ospf_interfaces module is missing while loading 2.3.0 module

### ISSUE THREAD

**Issue by skullq** [ansible-collections/cisco.nxos#311]
Hi Team,

I'm testing the latest 2.3.0 nxos collection now.
nxos_interfaces, nxos_l3_interfaces and nxos_ospfv2 are working great except nxos_ospf_interfaces.
Can you plz take a look into this ?

nxosv version 9.3(7)

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.1.0  
ansible.utils     2.2.0  
cisco.nxos        2.3.0  

---                     
  - hosts: n9k-1
    connection: network_cli

    tasks:
      - name: Set L3 interface
        nxos_interfaces:
          config:
          - name: Ethernet1/5
            description: DDDD
            mode: layer3
            enabled: true
        tags: interface
        
      - name: Config L3 Interface
        nxos_l3_interfaces:
          config: 
          - name: Ethernet1/5
            ipv4:
            - address: 10.1.1.1/24
              tag: 12345
          state: replaced
        tags: interface

      - name: Enable OSPF
        nxos_feature:
          feature: ospf
          state: enabled
        tags: ospf

      - name: Config OSPFv2
        nxos_ospfv2:
          config:
            processes: 
            - process_id: 100
              router_id: 1.1.1.1
        tags: ospf

      - name: OSPF Interface
        nxos_ospf_interfaces:
          config:
            - name: Ethernet1/5
              address_family: 
              - afi: ipv4
                process_id: 100
                area: 0.0.0.0
              - network: point-to-point
        tags: ospf

  ansible-playbook ospf.yaml -vvv

ansible-playbook [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.9 (default, Apr  3 2021, 01:02:10) [GCC 5.4.0 20160609]
  jinja version = 2.11.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
redirecting (type: modules) ansible.builtin.nxos_interfaces to cisco.nxos.nxos_interfaces
redirecting (type: modules) ansible.builtin.nxos_l3_interfaces to cisco.nxos.nxos_l3_interfaces
redirecting (type: modules) ansible.builtin.nxos_feature to cisco.nxos.nxos_feature
redirecting (type: modules) ansible.builtin.nxos_ospfv2 to cisco.nxos.nxos_ospfv2
ERROR! couldn't resolve module/action 'nxos_ospf_interfaces'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/mywork/ansible/ospf.yaml': line 40, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - name: OSPF Interface
        ^ here

**Comment by NilashishC** [comment]
@skullq Does using the fully qualified collection name (cisco.nxos.nxos_ospf_interfaces) for the module work?

**Comment by skullq** [comment]
@NilashishC 
Here is output with full module name. 
Output indicates there is no required argument and network is Null.
Let me try to put required argument however short name should work as nxoss_ospfv2. 

-- snip --
      - name: Config OSPFv2
        nxos_ospfv2:
          config:
            processes: 
            - process_id: 100
              router_id: 1.1.1.1
        tags: ospf
      - name: OSPF Interface
        cisco.nxos.nxos_ospf_interfaces:
        #nxos_ospf_interfaces:
          config:
            - name: Ethernet1/5
              address_family: 
              - afi: ipv4
                process_id: 100
                area: 0.0.0.0
              - network: point-to-point
    
fatal: [n9k-1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "address_family": [
                        {
                            "afi": "ipv4",
                            "area": "0.0.0.0",
                            "authentication": null,
                            "authentication_key": null,
                            "cost": null,
                            "dead_interval": null,
                            "default_passive_interface": null,
                            "hello_interval": null,
                            "instance": null,
                            "message_digest_key": null,
                            "mtu_ignore": null,
                            "multi_areas": null,
                            "network": null,    <<<<< 
                            "passive_interface": null,
                            "priority": null,
                            "process_id": 100,
                            "processes": null,
                            "retransmit_interval": null,
                            "shutdown": null,
                            "transmit_delay": null
                        },
                        {
                            "afi": null,
                            "authentication": null,
                            "authentication_key": null,
                            "cost": null,
                            "dead_interval": null,
                            "default_passive_interface": null,
                            "hello_interval": null,
                            "instance": null,
                            "message_digest_key": null,
                            "mtu_ignore": null,
                            "multi_areas": null,
                            "network": "point-to-point",
                            "passive_interface": null,
                            "priority": null,
                            "processes": null,
                            "retransmit_interval": null,
                            "shutdown": null,
                            "transmit_delay": null
                        }
                    ],
                    "name": "Ethernet1/5"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    },
    "msg": "missing required arguments: afi found in config -> address_family"
}

PLAY RECAP ****************************************************************************************************************************************************************************************************
n9k-1                      : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by allenrobel** [comment]
Hi skullq,

A few things to check:

1. nxos_ospf_interfaces doesn't have a ``tags`` key, AFAIK.
2. The ``area`` key (again, AFAIK) should be a dict containing ``area_id`` key
3. ``process_id`` and ``area`` should go within a ``processes`` dict

Can you try changing your task to similar to the below?  The below is working for me.

```yaml
---
-   hosts: n9k-1
    name: OSPF Interface
    tasks:
    -   cisco.nxos.nxos_ospf_interfaces:
            config:
            -   name: Ethernet1/5
                address_family:
                -   afi: ipv4
                    network: point-to-point
                    processes:
                    -   process_id: 1
                        area: 
                            area_id: 0.0.0.0
```

Thanks!

Allen

**Comment by skullq** [comment]
@allenrobel 
Hi Allen, It's working! Thank you!

**Comment by allenrobel** [comment]
> @allenrobel 
> 
> Hi Allen, It's working! Thank you!

@skullq Good to hear! 👍

**Comment by NilashishC** [comment]
@skullq The reason why the module shortname (nxos_ospf_interfaces) did not work and the FQCN (cisco.nxos.nxos_ospf_interfaces) worked is because you didn't specify collection in your playbook. The other modules you're using are older and have redirections in [ansible_builtin_runtime](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml) mappings and hence those were loaded fine. The recommended approach would be to use FQCN modules name per task or import the collections at the beginning of your playbook.

Please refer to the following documentation: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-collections-in-a-playbook

As such, I'll be closing this issue as resolved.
