### ISSUE TITLE
nxos_facts: Fails When Collecting Legacy Facts (CDP Neighbors)

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.nxos#329]
##### SUMMARY

We have an 8.4(2) Nexus 7706 and when we try to collect legacy facts (CDP) it fails on a KeyErorr for intf_id. When we look in the NXAPI sandbox we see what we suspect was `intf_id` now as `interface`. Here is a dump of the view from the device via the NXAPI sandbox:

```
{
  "jsonrpc": "2.0",
  "result": {
    "body": {
      "TABLE_cdp_neighbor_detail_info": {
        "ROW_cdp_neighbor_detail_info": [
          {
            "device_id": "FI-MyFirstFI-A",
            "sysname": "FI-MyFirstFI-A",
            "numaddr": 1,
            "v4addr": "9.9.9.9",
            "platform_id": "UCS-FI-6248UP",
            "capability": [
              "switch",
              "IGMP_cnd_filtering",
              "Supports-STP-Dispute"
            ],
            "interface": "Ethernet6/1",
            "port_id": "Ethernet1/11",
            "ttl": 140,
            "version": "Cisco Nexus Operating System (NX-OS) Software, Version 5.0(3)N2(4.02c)",
            "version_no": "v2",
            "nativevlan": 1,
            "duplexmode": "full",
            "mtu": 0,
            "syslocation": "snmplocation",
            "num_mgmtaddr": 1,
            "v4mgmtaddr": "9.9.9.9"
          },
...
```
We don't have any relevant links that confirm this API change was intentional on the Cisco side (release notes, etc). We can't be sure if we need to handle the difference in the API's or if it should be reported to Cisco (we've opened a case w/TAC too).

https://developer.cisco.com/docs/nx-api-cli-reference-for-the-cisco-nexus-7000-series-platform/#!cdp-commands/show-cdp-neighbors-detail
^^ It seems at least as of 8.3 it was still `intf_id`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_facts

##### ANSIBLE VERSION

```paste below
2.9.22
```

##### COLLECTION VERSION

```paste below
2.4.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

In Ansible < 2.11 the gather_subset is still !config so it trips this (Ansible 2.9 is the version used in Tower so this trips very often).
```yaml
---
- hosts: all
  gather_facts: yes
```

Alternatively:
```yaml
- cisco.nxos.nxos_facts:
    gather_subset: all
```

##### EXPECTED RESULTS

Module gathers CDP neighbor information correctly.

##### ACTUAL RESULTS

```paste below
{
    "_ansible_no_log": false,
    "module_stderr": "/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py:897: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 258, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 249, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 158, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 255, in populate\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_KVJ58l/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 347, in populate_structured_neighbors_cdp\nKeyError: 'intf_id'\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

**Comment by timway** [comment]
We confirmed with Cisco TAC that "interface" is the go-forward approach for NX-OS on Nexus 7k's (unclear if that will be replicated in N3K and N9K at any point). The TAC engineer confirmed this via documentation internal to Cisco and is not currently reflected in the Nexus 7k examples on DevNet (those are still running < 8.4(1) ).

Reply from TAC:

> That’s interesting question, internal information show NXOS redesign for NXAPI on N7K/N77  8.4(1), there is nothing related to any other platform. Also checking N9K running newest version 10.1(2) we can see it still showing “intf_id” as expected.

At this point it sounds like we'll need to detect if it's a N7K running >= 8.4(1) to get the normal gather_facts to run (In Ansible 2.9 - which is what Tower is pinned to it still hits this code by default).

**Comment by ChristopherJHart** [comment]
FYI, the traceback Ansible will throw when this issue is encountered will be similar to this:
```
Traceback (most recent call last):
  File \"/home/chart2/.ansible/tmp/ansible-local-15351582zpfb7bk/ansible-tmp-1628643602.8080957-1535227-50393058270471/AnsiballZ_nxos_facts.py\", line 102, in <module>
    _ansiballz_main()
  File \"/home/chart2/.ansible/tmp/ansible-local-15351582zpfb7bk/ansible-tmp-1628643602.8080957-1535227-50393058270471/AnsiballZ_nxos_facts.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/chart2/.ansible/tmp/ansible-local-15351582zpfb7bk/ansible-tmp-1628643602.8080957-1535227-50393058270471/AnsiballZ_nxos_facts.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 258, in <module>
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 249, in main
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 161, in get_facts
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 255, in populate
  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_mv77w86y/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 347, in populate_structured_neighbors_cdp
KeyError: 'intf_id'
```

**Comment by athompson-merlin** [comment]
I'm running an NX3127 with NXOS 9.3(4), and I'm getting errors like this but ending in `KeyError: 'interface'`, not 'intf_id'.

Each run results in this (excerpted, obviously):
```             "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-105860p8twi9ck/ansible-tmp-1644351931.6218069-105865-134510460890815/AnsiballZ_nxos_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-105860p8twi9ck/ansible-tmp-1644351931.6218069-105865-134510460890815/AnsiballZ_nxos_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-105860p8twi9ck/ansible-tmp-1644351931.6218069-105865-134510460890815/AnsiballZ_nxos_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=dict(_module_fqn='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 259, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 250, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 161, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 255, in populate\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_scovwayy/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 348, in populate_structured_neighbors_cdp\nKeyError: 'interface'\n",```

I'm unclear whether this means I'm running into the same problem or not - any thoughts?

**Comment by athompson-merlin** [comment]
NVM, I had a duplicate (overriding) cisco.nxos collection in $HOME/.ansible/collections that I wasn't aware of.
