### ISSUE TITLE
Gather facts failing on FEX-FABRIC ports

### ISSUE THREAD

**Issue by mpberin** [ansible-collections/cisco.nxos#334]
##### SUMMARY

Getting error pulling nxos_facts with FEX interfaces list constraint error
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_facts
##### ANSIBLE VERSION

```ansible 2.10.2
  config file = /Users/mberin/Documents/code/pyats/ansible/ansible.cfg
  configured module search path = ['/Users/mberin/Documents/code/pyats/ansible']
  ansible python module location = /Users/mberin/Documents/code/pyats/venv/lib/python3.8/site-packages/ansible
  executable location = /Users/mberin/Documents/code/pyats/venv/bin/ansible
  python version = 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39) [Clang 6.0 (clang-600.0.57)]

```

##### COLLECTION VERSION

```(venv) macbpro ansible % ansible-galaxy collection list -p ../venv/lib/python3.8/site-packages/ansible_collections/cisco/nxos 

# /Users/mberin/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 1.4.1  

```

##### CONFIGURATION

```ACTION_WARNINGS(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = ['/Users/mberin/Documents/code/pyats/ansible/hosts']
DEFAULT_LOG_PATH(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = /Users/mberin/Documents/code/pyats/ansible/ansible.log
DEFAULT_MODULE_PATH(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = ['/Users/mberin/Documents/code/pyats/ansible']
DEFAULT_ROLES_PATH(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = ['/Users/mberin/Documents/code/pyats/ansible/roles']
DEPRECATION_WARNINGS(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/mberin/Documents/code/pyats/ansible/ansible.cfg) = /Users/mberin/Documents/code/pyats/venv/bin/python

```

##### OS / ENVIRONMENT

RI-0006E-D01# sh inventory 
NAME: "Chassis",  DESCR: "Nexus7000 C7010 (10 Slot) Chassis "    
PID: N7K-C7010           ,  VID: V03 ,  SN: JAF1740AEQL 
Software
  BIOS:      version 2.12.0
  kickstart: version 7.2(0)D1(1)
  system:    version 7.2(0)D1(1)
  BIOS compile time:       05/29/2013
  kickstart image file is: bootflash:///n7000-s2-kickstart.7.2.0.D1.1.bin
  kickstart compile time:  5/19/2015 11:00:00 [06/14/2015 17:46:33]
  system image file is:    bootflash:///n7000-s2-dk9.7.2.0.D1.1.bin
  system compile time:     5/19/2015 11:00:00 [06/14/2015 19:40:32]

##### STEPS TO REPRODUCE

``` - name: Gather interfaces resource
        cisco.nxos.nxos_facts:
          gather_subset: 
            - all
          gather_network_resources: 
            - all
        register: nxos_facts_output


```

##### EXPECTED RESULTS

{
    "ansible_facts": {
        "ansible_net__hostname": "SCDC-J5-D06",
        "ansible_net__os": "7.3(4)D1(1)",
        "ansible_net__platform": "Nexus7000 C7010 (10 Slot) Chassis",
         "ansible_network_resources": {
            "interfaces": [
                {
                    "description": "VPC KEEPALIVE",
                    "name": "mgmt0"
                },
  
               {
                    "name": "Ethernet112/1/34"
                }
##### ACTUAL RESULTS

    "msg": "value of mode must be one of: access, trunk, got: fex-fabric found in config"

```paste below

```

**Comment by NilashishC** [comment]
Hi @mpberin. Which version of the cisco.nxos collection are you using? This issue has been fixed starting from v1.3.0, as a part for this PR: https://github.com/ansible-collections/cisco.nxos/pull/167.

**Comment by NilashishC** [comment]
This option is available in the `mode` key: https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py#L45-L48.

**Comment by NilashishC** [comment]
Hey @mpberin. Since we haven't heard from you yet, I believe using the latest version of this collection solved the issue for you. Hence, I'll be closing this ticket. If you continue to face this issue, please feel free to re-open this ticket. Thank you!
