### ISSUE TITLE
cisco.nxos.nxos_route_maps: add support for 'set ip next-hop'

### ISSUE THREAD

**Issue by andrewbonney** [ansible-collections/cisco.nxos#384]
##### SUMMARY
The nxos_route_maps module does not appear to support 'set ip next-hop ...' as required for BGP EVPN configuration in https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/vxlan/configuration/guide/b-cisco-nexus-9000-series-nx-os-vxlan-configuration-guide-93x/b-cisco-nexus-9000-series-nx-os-vxlan-configuration-guide-93x_chapter_0101.html

It would be useful to have this added to avoid the need for a more manual approach.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.nxos.nxos_route_maps

##### ADDITIONAL INFORMATION
N/A

**Comment by NilashishC** [comment]
Fixed by https://github.com/ansible-collections/cisco.nxos/pull/646. This feature will be available with the v4.2.0 release of this collection.
