### ISSUE TITLE
Create template peer (bgp peer)

### ISSUE THREAD

**Issue by evertos** [ansible-collections/cisco.nxos#389]
##### SUMMARY
How to create router bgp, peer templates.

##### ISSUE TYPE
- Bug Report
The plugin specifies how to assign a peer template but not how to create them.

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_bgp_global_module.html#

##### CONFIGURATION
Example configuration on the switch:

router bgp 10001
  router-id 1.1.0.1
  bestpath as-path multipath-relax
  bestpath always-compare-med
  address-family ipv4 unicast
    maximum-paths 16
    maximum-paths ibgp 16
  **template peer Node1**
    remote-as 10011
    description Node1
    address-family ipv4 unicast
      next-hop-self
  **template peer Node2**
    remote-as 10022
    description Node2
    address-family ipv4 unicast
      next-hop-self

**Comment by evertos** [comment]
The workaround I now use:
**Task**
    - name: Add template peers
      cisco.nxos.nxos_config:
        lines:
        - template peer {{ item.name }}
        - remote-as {{item.peer_as}}
        - description {{ item.name }}
        - address-family ipv4 unicast
        - next-hop-self
        parents: 'router bgp {{ as_base }}0000'
        match: exact
      loop: "{{ bgppeers }}"
      tags: bgppeers

**host_vars:**
as_base: 421251

bgppeers:
  - name: Test1
    peer_ips:
    - 172.18.253.12
    vrf: Test1
    peer_as: 65101
  - name: Test2
    peer_ips:
    - 172.18.253.2
    vrf: DMPSERVICES
    peer_as: 65102

**Comment by evertos** [comment]
Good day, is there any update on this or an idea when there will be looked at?

really appreciate all the work that has been done on these modules!

**Comment by NilashishC** [comment]
@evertos Apologize for the delay on this. This has finally been committed to and we will start working on this shortly. I do not have an ETA right now, but we will keep this thread updated.
