### ISSUE TITLE
Cisco NXOS MDS Module Issue 

### ISSUE THREAD

**Issue by feisacrabel** [ansible-collections/cisco.nxos#46]
Im attempting to manage Cisco MDS switches running m9100-s5ek9-kickstart-mz.8.4.1.bin code.
The issue I'm running into is piping into json doesn't work

sh version | json
^
% Incomplete command at '^' marker.

but piping into json native works

sh version | json native
{
"header_str": "Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nDocuments: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html\nCopyright (c) 2002-2019, Cisco Systems, Inc. All rights reserved.\nThe copyr
ights to certain works contained herein are owned by\nother third parties and are used and distributed under license.\nSome parts of this software are covered under the GNU Public\nLicense. A copy of the license is available at\nhttp://www.gnu.org/licenses/gpl.html.\n",
"bios_ver_str": "2.1.17",
"loader_ver_str": "N/A",
"kickstart_ver_str": "8.4(1)",
"sys_ver_str": "8.4(1)",
"bios_cmpl_time": "01/08/14",
"kick_file_name": "bootflash:///m9100-s5ek9-kickstart-mz.8.4.1.bin",
"kick_cmpl_time": " 6/30/2019 23:00:00",
"kick_tmstmp": "06/15/2019 04:15:24",
"isan_file_name": "bootflash:///m9100-s5ek9-mz.8.4.1.bin",
"isan_cmpl_time": " 6/30/2019 23:00:00",
"isan_tmstmp": "06/15/2019 05:44:25",
"chassis_id": "MDS 9148S 16G 48 FC (1 Slot) Chassis",
"module_id": "2/4/8/16 Gbps FC/Supervisor",
"cpu_name": "Motorola, e500v2",
"memory": 4088640,
"mem_type": "kB",
"proc_board_id": "JAE202108JM",
"host_name": "test-sanmc001",
"bootflash_size": 4001760,
"kern_uptm_days": 79,
"kern_uptm_hrs": 2,
"kern_uptm_mins": 38,
"kern_uptm_secs": 19,
"rr_usecs": 897283,
"rr_ctime": "Sat Feb 15 16:12:52 2020",
"rr_reason": "Reset Requested by CLI command reload",
"rr_sys_ver": "8.4(1)",
"rr_service": "",
"manufacturer": "Cisco Systems, Inc."
}

Can we work to replace just the pipe to JSON to JSON native? This way all nxos modules work across all nxos switches

ISSUE TYPE
Bug Report
COMPONENT NAME
ansible cisco nxos modules

ANSIBLE VERSION
2.9

CONFIGURATION
OS / ENVIRONMENT
cisco nxos

**Comment by feisacrabel** [comment]
any update on this?

**Comment by feisacrabel** [comment]
Cisco TAC came back with this, i think this would be a great fix for the modules overall involving nxos

I have checked with the engineering team and they have informed that “show command | json” is not supported on platforms not having python support.
 
Please use “show cmd | json native” instead. 
Json native is supported on all platforms from 8.4.1 version onwards.
F241-15-10-9396S-2# show version | json native
{
        "header_str":   "Cisco Nexus Operating System (NX-OS) Software\nTAC supp
ort: http://www.cisco.com/tac\nDocuments: http://www.cisco.com/en/US/products/ps
9372/tsd_products_support_series_home.html\nCopyright (c) 2002-2019, Cisco Syste
ms, Inc. All rights reserved.\nThe copyrights to certain works contained herein
are owned by\nother third parties and are used and distributed under license.\nS
ome parts of this software are covered under the GNU Public\nLicense. A copy of
the license is available at\nhttp://www.gnu.org/licenses/gpl.html.\n",
        "bios_ver_str": "5.2.19",
        "loader_ver_str":       "N/A",
        "kickstart_ver_str":    "8.4(1)",
        "sys_ver_str":  "8.4(1)",
        "bios_cmpl_time":       "05/15/2015",
        "kick_file_name":       "bootflash:///m9300-s1ek9-kickstart-mz.8.4.1_S25
.bin",
        "kick_cmpl_time":       " 6/30/2019 23:00:00",
        "kick_tmstmp":  "05/28/2019 06:25:19",
        "isan_file_name":       "bootflash:///m9300-s1ek9-mz.8.4.1_S25.bin",
        "isan_cmpl_time":       " 6/30/2019 23:00:00",
        "isan_tmstmp":  "05/28/2019 08:16:29",
        "chassis_id":   "MDS 9396S 96X16G FC (2 RU) Chassis",
        "module_id":    "2/4/8/10/16 Gbps FC/Supervisor-4",
        "cpu_name":     "Motorola, 476fpe",
        "memory":       3890532,
        "mem_type":     "kB",
        "proc_board_id":        "JAE19170EJ1",
        "host_name":    "F241-15-10-9396S-2",
        "bootflash_size":       3915776,
        "kern_uptm_days":       0,
        "kern_uptm_hrs":        0,
        "kern_uptm_mins":       8,
        "kern_uptm_secs":       30,
        "rr_usecs":     90424,
        "rr_ctime":     "Tue May  5 16:10:16 2020",
        "rr_reason":    "Reset due to upgrade",
        "rr_sys_ver":   "8.3(2)",
        "rr_service":   "",
        "manufacturer": "Cisco Systems, Inc."
}

**Comment by NilashishC** [comment]
cc @srbharadwaj

**Comment by srbharadwaj** [comment]
looking into it

**Comment by srbharadwaj** [comment]
@feisacrabel which module are you specifically asking about?

**Comment by feisacrabel** [comment]
@srbharadwaj its effects all modules that | json. Its basically every nxos module

**Comment by srbharadwaj** [comment]
@feisacrabel as far as i know none of the modules currently uses "| json" , so i'am note sure how its affected.

**Comment by feisacrabel** [comment]
almost every module does, nxos_gather_facts nxos_ntp

fatal: [device]: FAILED! => {"changed": false, "msg": "show ntp authentication-status | json\r\r\n                                                   ^\r\n% Incomplete command at '^' marker.\r\n\rdevice# "}

**Comment by srbharadwaj** [comment]
Ah thanks, i was just checking MDS modules, but now i know where the issue is , will get back. Thanks.

**Comment by srbharadwaj** [comment]
@feisacrabel Can you let me what is the 'transport' or 'ansible_connection:' that you are using?

**Comment by feisacrabel** [comment]
ansible_connection: network_cli
ansible_network_os: nxos

**Comment by feisacrabel** [comment]
any idea what this might be?

**Comment by srbharadwaj** [comment]
We are working on a solution, discussion is going on

**Comment by feisacrabel** [comment]
any word on this?

**Comment by feisacrabel** [comment]
i see the merge failed, do you need any help testing?

**Comment by srbharadwaj** [comment]
sorry for the late reply, some of the unit tests failed so checking those with the ansible team

**Comment by srbharadwaj** [comment]
@feisacrabel  we have added a fix, can you test it?

**Comment by feisacrabel** [comment]
@srbharadwaj i just did some testing and this errors out 

The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 248, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py", line 239, in main
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py", line 125, in get_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/telemetry/telemetry.py", line 87, in populate_facts
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 862, in __init__
  File "/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 895, in _yaml_load
AttributeError: module 'yaml' has no attribute 'FullLoader'
fatal: [la3-sanmc001]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-755841c6r5llq0/ansible-tmp-1599770920.853401-755847-160787626783475/AnsiballZ_nxos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 248, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py\", line 239, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/facts.py\", line 125, in get_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/telemetry/telemetry.py\", line 87, in populate_facts\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py\", line 862, in __init__\n  File \"/tmp/ansible_cisco.nxos.nxos_facts_payload__soed2fo/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py\", line 895, in _yaml_load\nAttributeError: module 'yaml' has no attribute 'FullLoader'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
...ignoring
