### ISSUE TITLE
Cisco.nxos.nxos_file_copy and MDS Switches.

### ISSUE THREAD

**Issue by rozmusjs** [ansible-collections/cisco.nxos#508]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /home/jrozmus/ansible-network/ansible.cfg
  configured module search path = ['/home/jrozmus/ansible-network/library']
  ansible python module location = /home/jrozmus/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

```

##### COLLECTION VERSION

```paste below
# /home/jrozmus/ansible-network/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 3.0.0

# /usr/local/lib/python3.6/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0

# /home/jrozmus/.local/lib/python3.6/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/collections']
DEFAULT_ACTION_PLUGIN_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_FORKS(/home/jrozmus/ansible-network/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/inventories']
DEFAULT_MODULE_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/library']
DEFAULT_ROLES_PATH(/home/jrozmus/ansible-network/ansible.cfg) = ['/home/jrozmus/ansible-network/roles']
DEFAULT_SCP_IF_SSH(/home/jrozmus/ansible-network/ansible.cfg) = True
GALAXY_SERVER_LIST(/home/jrozmus/ansible-network/ansible.cfg) = ['release_galaxy']
HOST_KEY_CHECKING(/home/jrozmus/ansible-network/ansible.cfg) = False
INTERPRETER_PYTHON(/home/jrozmus/ansible-network/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/home/jrozmus/ansible-network/ansible.cfg) = 60000000
PERSISTENT_CONNECT_TIMEOUT(/home/jrozmus/ansible-network/ansible.cfg) = 6000

```

##### OS / ENVIRONMENT

fr2-sanmc002# sh inv
NAME: "Chassis",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis"
PID: DS-C9148S-K9        ,  VID: V02 ,  SN: JPG250400QB

NAME: "Slot 1",  DESCR: "2/4/8/16 Gbps FC/Supervisor"
PID: DS-C9148S-K9-SUP    ,  VID: V02 ,  SN: JAE250400DA

NAME: "Slot 2",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Power Supply"
PID: DS-C48S-300AC       ,  VID: V00 ,  SN: QCS24522LSB

NAME: "Slot 3",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Power Supply"
PID: DS-C48S-300AC       ,  VID: V00 ,  SN: QCS24522LRP

NAME: "Slot 4",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Fan Module"
PID: DS-C48S-FAN         ,  VID: V00 ,  SN: N/A

NAME: "Slot 5",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Fan Module"
PID: DS-C48S-FAN         ,  VID: V00 ,  SN: N/A

NAME: "Slot 6",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Fan Module"
PID: DS-C48S-FAN         ,  VID: V00 ,  SN: N/A

NAME: "Slot 7",  DESCR: "MDS 9148S 16G 48 FC (1 Slot) Chassis Fan Module"
PID: DS-C48S-FAN         ,  VID: V00 ,  SN: N/A
!
Software
  BIOS:      version 2.1.18
  loader:    version N/A
  kickstart: version 9.2(1)
  system:    version 9.2(1)
  BIOS compile time:       04/06/20
  kickstart image file is: bootflash:///m9100-s5ek9-kickstart-mz.9.2.1.bin
  kickstart compile time:  8/9/2021 12:00:00 [08/23/2021 18:47:15]
  system image file is:    bootflash:///m9100-s5ek9-mz.9.2.1.bin

##### STEPS TO REPRODUCE

```yaml
- name: Copy Nexus File MDS 9184
  cisco.nxos.nxos_file_copy:
    file_pull: true
    file_pull_protocol: http
    remote_file: "/network/{{ nxos_device }}/{{ nxos_image }}"
    local_file: "{{ nxos_image }}"
    remote_scp_server: pxefiles.files.local
    remote_scp_server_user: anonymous
    vrf: "{{ default | default(omit) }}"
  when: 
    - dir.stdout_lines is not search(nxos_image)
    - inventory_hostname in groups["nxos_san"]
```

##### EXPECTED RESULTS

The script should produce the following syntax:
http://anonymous@pxefiles.hq.crabel.com/network/9148/jerry.txt bootflash:/jerry.txt
The code should drop "vrf management" from the end of this command. This syntax will work on 3 and 9 Ks but will not work on the MDS (SAN switches).

##### ACTUAL RESULTS

TASK [nxos-file-copy : Copy Nexus File MDS 9184] ***********************************************************************************************************************************************************************************************************************************
task path: /home/jrozmus/ansible-network/roles/nxos-file-copy/tasks/main.yml:42
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
fatal: [ty3-sanmc002]: FAILED! => {
    "changed": false,
    "module_stderr": "http://anonymous@pxefiles.hq.crabel.com/network/9148/jerry.txt bootflash:/jerry.txt vrf management\r\r\n                                                                                                       ^\r\n% Invalid command at '^' marker.\r\n\rty3-sanmc002# ",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
...ignoring

```paste below
TASK [nxos-file-copy : Copy Nexus File MDS 9184] ***********************************************************************************************************************************************************************************************************************************
task path: /home/jrozmus/ansible-network/roles/nxos-file-copy/tasks/main.yml:42
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
fatal: [ty3-sanmc002]: FAILED! => {
    "changed": false,
    "module_stderr": "http://anonymous@pxefiles.hq.crabel.com/network/9148/jerry.txt bootflash:/jerry.txt vrf management\r\r\n                                                                                                       ^\r\n% Invalid command at '^' marker.\r\n\rty3-sanmc002# ",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
...ignoring


```

**Comment by srbharadwaj** [comment]
yes vrf option is present for MDS switches

**Comment by rozmusjs** [comment]
Correct the "vrf" option should be an optional variable.

**Comment by rozmusjs** [comment]
Do we have an ETA when this will be corrected?

**Comment by NilashishC** [comment]
@rozmusjs The changes in PR #531 should fix this issue.
