### ISSUE TITLE
Add mode parameter to cisco.nxos.nxos_interfaces to manage the state of the interface

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.nxos#598]
##### SUMMARY

Add mode parameter to cisco.nxos.nxos_interfaces to manage the state of the interface.

##### ISSUE TYPE
We have to rely on creating templates to run commands depending if the interface is layer 2 or 3.

##### COMPONENT NAME

cisco.nxos.nxos_interfaces

##### ADDITIONAL INFORMATION

    - name: Update l3_interfaces
      cisco.nxos.nxos_interfaces:
      config:
      - name: Vlan51
        mode: layer3
      state: merged

    - name: Update l2_interfaces
      cisco.nxos.nxos_interfaces:
      config:
      - name: Vlan51
        mode: layer2
      state: merged

**Comment by NilashishC** [comment]
@digitalfiend64 The mode parameter already exists in the nxos_interfaces modules - https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_interfaces_module.html#parameter-config/mode
