### ISSUE TITLE
N7K ISSU : nxos_install_os module fails even though upgrade succeeded

### ISSUE THREAD

**Issue by anilpati** [ansible-collections/cisco.nxos#628]
##### SUMMARY
Hello Team,
we are using nxos_install_os  module for N7K ISSU upgrade. but the playbook script is failing with error. but we see that N7K box is getting upgraded 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_install_os

##### ANSIBLE VERSION
 2.11.12
 

##### COLLECTION VERSION
# /usr/local/lib/python3.7/dist-packages/ansible_collections
Collection                    Version
----------------------------- ------- 
cisco.aci                     2.1.0  
cisco.asa                     2.1.0  
cisco.intersight              1.0.18 
cisco.ios                     2.6.0  
cisco.iosxr                   2.6.0  
cisco.meraki                  2.5.0  
cisco.mso                     1.2.0  
cisco.nso                     1.0.3  
cisco.nxos                    2.8.2  
cisco.ucs                     1.6.0  

##### CONFIGURATION
(ansible_test) cisco@robot-dev:~/ansible_env/Ansible$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/cisco/ansible_env/Ansible/ansible.cfg) = ['/home/cisco/ansible_env/Ansible/inventory']
DEFAULT_TIMEOUT(/home/cisco/ansible_env/Ansible/ansible.cfg) = 5
DEPRECATION_WARNINGS(/home/cisco/ansible_env/Ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/cisco/ansible_env/Ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/cisco/ansible_env/Ansible/ansible.cfg) = 2000
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/cisco/ansible_env/Ansible/ansible.cfg) = 2000
PERSISTENT_CONNECT_TIMEOUT(/home/cisco/ansible_env/Ansible/ansible.cfg) = 2000

##### OS / ENVIRONMENT
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"

##### STEPS TO REPRODUCE
```
- name: TASK 2 - PERFORM THE UPGRADE 
        nxos_install_os:
          issu: desired
          kickstart_image_file: n7000-s2-kickstart.8.2.8.bin
          system_image_file: n7000-s2-dk9.8.2.8.bin
        register: result1

```
##### EXPECTED RESULTS

Box should upgrade and task should succeed

##### ACTUAL RESULTS
```
fatal: [DCC_2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "issu": "desired",
            "kickstart_image_file": "n7000-s2-kickstart.8.2.8.bin",
            "provider": {
                "auth_pass": null,
                "authorize": false,
                "host": null,
                "password": null,
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_proxy": true,
                "use_ssl": false,
                "username": null,
                "validate_certs": false
            },
            "system_image_file": "n7000-s2-dk9.8.2.8.bin"
        }
    },
    "msg": "Failed to upgrade device using command: ['terminal dont-ask', 'install all  system n7000-s2-dk9.8.2.8.bin kickstart n7000-s2-kickstart.8.2.8.bin']",
    "raw_data": [
        "timeout value 2000 seconds reached while trying to send command: b'install all  system n7000-s2-dk9.8.2.8.bin kickstart n7000-s2-kickstart.8.2.8.bin'"
    ]
}
```

**Comment by NilashishC** [comment]
Similar to #552

**Comment by NilashishC** [comment]
As discussed over calls with Anil, this issue is now resolved.
