### ISSUE TITLE
Cisco NXOS ansible module cannot run commands on NXOS Version 10.3

### ISSUE THREAD

**Issue by arpitmidha** [ansible-collections/cisco.nxos#664]
##### SUMMARY
We have cisco devices with NXOS version 10.3 , we are trying to run multiple commands via ansible module cisco.nxos 2.7.1 and getting repeated timeout errors , we are able to manually ssh into the devices and run those commands,
One of the commands we are facing issue is " show ip prefix-list"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Cisco.nxos.nxos_command

##### ANSIBLE VERSION
ansible [core 2.11.12]

cisco.nxos version 2.7.1

**Comment by nathan815-msft** [comment]
@NilashishC  Thank you for the quick response. We will try testing this with cisco.nxos v4.2.0 and give an update here if it works.

To add some info to the original post - here is the full error message we are receiving for any commands on NXOS 10.3


> `failed: [*** -> localhost] (item=show vrf interface vlan 1126 | i TNT-PRIV) => {"ansible_index_var": "item_index", "ansible_loop_var": "item", "changed": false, "failed_when_result": "The conditional check 'current_config.stdout[item_index] == ''' failed. The error was: error while evaluating conditional (current_config.stdout[item_index] == ''): 'dict object' has no attribute 'stdout'. 'dict object' has no attribute 'stdout'", "item": "show vrf interface vlan 1126 | i TNT-PRIV", "item_index": 0 }`

The issue is that the module output dictionary is missing the `stdout` field when targeting Nexus switches running NXOS 10.3.

**Comment by arpitmidha** [comment]
@NilashishC 
We enabled the network device interaction logs 


EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559 `" && echo ansible-tmp-1682412624.6944456-145983820951559="` echo /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/network/nxos/nxos_config.py
PUT /root/.ansible/tmp/ansible-local-8154qrdgdy77/tmp066q1jq2 TO /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559/AnsiballZ_nxos_config.py
EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559/ /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559/AnsiballZ_nxos_config.py && sleep 0'
 EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-8154qrdgdy77/ansible-tmp-1682412624.6944456-145983820951559/AnsiballZ_nxos_config.py && sleep 0'
 EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-81597nbbrokz/ansible-tmp-1682412446.7001665-93340127680926/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: Removing the mgmt route maps for the tenant. (1 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "force": false,
            "host": null,
            "intended_config": null,
            "lines": [
                "no route-map RMAP-TNT905-MGMT-TO-PRIV-LEAK permit 30"
            ],
            "match": "line",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "replace_src": null,
            "running_config": null,
            "save": false,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "msg": "command timeout triggered, timeout value is 180 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.",

**Comment by NilashishC** [comment]
@arpitmidha Does running the playbook with `ansible_network_cli_ssh_type: libssh` give the same result? 

Are these logs from a run that uses cisco.nxos v4.2.0 or v2.7.1? What is the version of ansible.netcommon being used? 

The ansible-core v2.11 is at it's EOL and EOS. Could you please upgrade to ansible-core==2.14.x or 2.15.x (latest) and try this again?

**Comment by NilashishC** [comment]
@Qalthos any ideas on what might be causing this issue?

**Comment by arpitmidha** [comment]
There is an issue when ansible_become is set to tru, ansible cannot program the nxos 10.3 devices when ansible_become is set to true, if ansible_become is set to false, it is able to perform the configuration.
The reason for this is, in Cisco nxos 10.x devices, "show privilege" command is not available, and when ansible_become is set to true in ansible inventory then the nxos module tries to run "show privilege" command

![image](https://github.com/ansible-collections/cisco.nxos/assets/107024066/3efeaa67-de51-481c-b6ab-91a6e6f0c4ff)

**Comment by NilashishC** [comment]
This has been explained with more details in https://github.com/ansible-collections/cisco.nxos/issues/304#issuecomment-870433915.

There are two solutions to this:

- Turn off privilege escalation (ansible_become=False) for hosts that are running NX-OS >= 10.0.0

- Or, set [ansible_network_become_errors](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/network_cli_connection.html#parameter-become_errors) to determine how privilege escalation failures are handled. This option was added in ansible.netcommon v2.5.0, so if you're running an older version of netcommon than this, you would have to upgrade it.


Hope that resolves this issue for you.

**Comment by NilashishC** [comment]
Please let us know if turning off privilege escalation or suppressing the errors fixes the original problem reported in this ticket. Thanks!
