### ISSUE TITLE
nxos_bgp_neighbor_address_family: add support for lesser-used BGP features

### ISSUE THREAD

**Issue by andrewbonney** [ansible-collections/cisco.nxos#741]
##### SUMMARY
During updates to use the newer bgp modules, we identified the following commands which remain unsupported:

* Remote-as as a route-map
* Passwords in BGP neighbor configuration

Example:
```
router bgp 67400
  neighbor 2001:4000:4000:fff1::/64 remote-as route-map my-route-map
    password 3 some-hex-string
```

* Rewrite-rt-asn for ipv4 mvpn (similar to the already supported rewrite-evpn-rt-asn)

Example:
```
router bgp 67400
  neighbor 10.0.0.1
    address-family ipv4 mvpn
      rewrite-rt-asn
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* nxos_bgp_neighbor_address_family

##### ADDITIONAL INFORMATION
The former options are being used in our case to interact with OpenStack Neutron BGP instances. The latter is used for tenant routed multicast as shown in https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/104x/configuration/vxlan/cisco-nexus-9000-series-nx-os-vxlan-configuration-guide--release-104x/m_configuring_tenant_routed_multicast_93x.html

**Comment by NilashishC** [comment]
@andrewbonney Please find the below responses:

- `Remote-as as a route-map` - this seems to be a feature request for `nxos_bgp_global` and not the `neighbor_address_family` module. I will add this option as a part of that.

- `Passwords in BGP neighbor configuration` - this is already supported in the `nxos_bgp_global` module. Ref: https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_bgp_global_module.html#parameter-config/neighbors/password

- `Rewrite-rt-asn for ipv4 mvpn` - This is a valid for the address_family module. I will work on this.

**Comment by andrewbonney** [comment]
Thanks. Looks like I missed the password option in the docs and will try it out.

**Comment by andrewbonney** [comment]
Thanks for adding this so promptly
