### ISSUE TITLE
unable to install module with ansible-galaxy

### ISSUE THREAD

**Issue by pat4public** [ansible-collections/cisco.nxos#789]
##### SUMMARY
Install issue

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION
[root@116cb8161f2a mds-testing-local]# ansible-galaxy collection install cisco.nxos -vvv
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 
4.8.5 20150623 (Red Hat 4.8.5-44)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ansible-galaxy [core 2.11.8] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /etc/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Starting galaxy collection install process
Found installed collection netapp.ontap:21.16.0 at '/etc/ansible/ansible_collections/netapp/ontap'
Process install dependency map
Opened /root/.ansible/galaxy_token
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an unexpected error when getting available versions of collection cisco.nxos:
'/api/v3/plugin/ansible/content/published/collections/index/cisco/nxos/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/cisco/nxos/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'cisco.nxos'

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
ansible-galaxy collection install cisco.nxos

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by NilashishC** [comment]
@pat4public This seems to be an issue with the `ansible-galaxy` CLI client. If this persists, please open a ticket in https://github.com/ansible/ansible for help. With that, I'll close this issue.
