### ISSUE TITLE
Task will be failed when set shorter BGP timer than ISSU (8sec) in nxos_config module

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible-collections/cisco.nxos#82]
This is the re-open issue of https://github.com/ansible/ansible/issues/66228

##### SUMMARY

When the user set BGP timer with shorter value (e.g. `timer 2 6` ), the task will be failed and subsequent config will not applied for NXOS. That message is warning message so it should be ignored.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- nxos_config

##### ANSIBLE VERSION
Ansible 2.8

##### OS / ENVIRONMENT

NX-OS

##### STEPS TO REPRODUCE

Try to set the following config to nexus device:
```
router bgp xxxxx
  neighbor xxx.xxx.xxx.xxx remote-as xxxxx
    timers 2 6
```
##### EXPECTED RESULTS

no error.

##### ACTUAL RESULTS

The task has been failed and subsequent config was not applied.
```
 "msg": "timers 2 6\r\r\n% ISSU will be affected if hold time is less than system switchover time (8 seconds)"
```

**Comment by NilashishC** [comment]
@hiyokotaisa The response seems to be hitting [this](https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/terminal/nxos.py#L43) error regex. This is pretty generic regex, and removing it from the list in the terminal plugin may lead to unintended effects. Hence, I feel that handling this through the configurable option is a better solution.

**Comment by NilashishC** [comment]
@hiyokotaisa With the above, I'm closing this issue. Please feel free to re-open it if you feel otherwise and want to discuss this further. Thank you!
